ifeq ($(PROJ_PATH),)
include feature.mk
else
include $(PROJ_PATH)/feature.mk
endif

PLATFORM_DEVICE = BAND
GT_PROJECT_ENABLE = n
GT_PROJ_NAME = W269
GT_AT_GPIO_SUPPORT = y
CFLAGS += -DGT_W269_COMMON_FEATURE


MT2511_E1 = y
MT2511_INTERFACE = SPI
MTK_SMART_BATTERY_ENABLE = y
BMA255_ORIENTATION = OPT1
#MT2511_USE_IRQ = y
BMA255_USE_POLLING = y

#CFLAGS += -DHEART_RATE_MONITOR_OUT_PATTERN 


ifeq ($(GT_PROJECT_ENABLE),y)
# fusion algorithm
#FUSION_PEDOMETER_USE = M_INHOUSE_PEDOMETER
FUSION_SLEEP_TRACKER_USE = M_INHOUSE_SLEEP_TRACKER
FUSION_HEART_RATE_MONITOR_USE = M_INHOUSE_HEART_RATE_MONITOR
FUSION_HEART_RATE_VARIABILITY_USE = M_INHOUSE_HEART_RATE_VARIABILITY
FUSION_BLOOD_PRESSURE_USE = M_INHOUSE_BLOOD_PRESSURE
endif

# bt module enable
MTK_BT_ENABLE                       = y
MTK_BLE_ONLY_ENABLE                 = n
MTK_BT_HFP_ENABLE                   = n
MTK_BT_AVRCP_ENABLE                 = n
MTK_BT_AVRCP_ENH_ENABLE             = n
MTK_BT_A2DP_ENABLE                  = n
MTK_BT_PBAP_ENABLE                  = n
MTK_BT_SPP_ENABLE                   = y
