/* Copyright Statement:
 *
 * (C) 2005-2016  MediaTek Inc. All rights reserved.
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. ("MediaTek") and/or its licensors.
 * Without the prior written permission of MediaTek and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) MediaTek Software
 * if you have agreed to and been bound by the applicable license agreement with
 * MediaTek ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of MediaTek Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT MEDIATEK SOFTWARE RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

#ifndef __SUPC_MAP_H__
#define __SUPC_MAP_H__

#define MAP_MSG_ID_TST_INJECT_STRING                     MSG_ID_TST_INJECT_STRING
#define MAP_MSG_ID_TIMER_EXPIRY                          MSG_ID_TIMER_EXPIRY
#define MAP_MSG_ID_WNDRV_SUPC_DATA_IND                   MSG_ID_WNDRV_SUPC_DATA_IND
#define MAP_MSG_ID_SUPC_ABM_WIFI_INIT_REQ                MSG_ID_SUPC_ABM_WIFI_INIT_REQ
#define MAP_MSG_ID_SUPC_ABM_WIFI_DEINIT_REQ              MSG_ID_SUPC_ABM_WIFI_DEINIT_REQ
#define MAP_MSG_ID_WNDRV_SUPC_INIT_CNF                   MSG_ID_WNDRV_SUPC_INIT_CNF
#define MAP_MSG_ID_WNDRV_SUPC_DEINIT_CNF                 MSG_ID_WNDRV_SUPC_DEINIT_CNF
#define MAP_MSG_ID_WNDRV_SUPC_NETWORK_CONNECT_IND        MSG_ID_WNDRV_SUPC_NETWORK_CONNECT_IND
#define MAP_MSG_ID_WNDRV_SUPC_NETWORK_CONNECT_FAIL_IND   MSG_ID_WNDRV_SUPC_NETWORK_CONNECT_FAIL_IND
#define MAP_MSG_ID_WNDRV_SUPC_NETWORK_DISCONNECT_IND     MSG_ID_WNDRV_SUPC_NETWORK_DISCONNECT_IND
#define MAP_MSG_ID_WNDRV_SUPC_NETWORK_STATISTICS_IND     MSG_ID_WNDRV_SUPC_NETWORK_STATISTICS_IND
#define MAP_MSG_ID_WNDRV_SUPC_SITE_SURVEY_IND            MSG_ID_WNDRV_SUPC_SITE_SURVEY_IND
#define MAP_MSG_ID_WNDRV_SUPC_PMKID_CANDIDATE_IND        MSG_ID_WNDRV_SUPC_PMKID_CANDIDATE_IND
#define MAP_MSG_ID_WNDRV_SUPC_STATUS_IND                 MSG_ID_WNDRV_SUPC_STATUS_IND
#define MAP_MSG_ID_WNDRV_SUPC_QUERY_CAPABILITY_IND       MSG_ID_WNDRV_SUPC_QUERY_CAPABILITY_IND
#define MAP_MSG_ID_SUPC_ABM_WIFI_CONNECT_REQ             MSG_ID_SUPC_ABM_WIFI_CONNECT_REQ
#define MAP_MSG_ID_SUPC_ABM_WIFI_DISCONNECT_REQ          MSG_ID_SUPC_ABM_WIFI_DISCONNECT_REQ
#define MAP_MSG_ID_SUPC_ABM_WIFI_AP_LIST_REQ             MSG_ID_SUPC_ABM_WIFI_AP_LIST_REQ
//#define MAP_MSG_ID_CERTMAN_GET_CERT_BY_ID_CNF            MSG_ID_CERTMAN_GET_CERT_BY_ID_CNF
//#define MAP_MSG_ID_CERTMAN_GET_PRIVKEY_CNF               MSG_ID_CERTMAN_GET_PRIVKEY_CNF
//#define MAP_MSG_ID_CERTMAN_GET_CERT_CHAIN_CNF            MSG_ID_CERTMAN_GET_CERT_CHAIN_CNF
#define MAP_MSG_ID_SUPC_ABM_WIFI_DISCONNECT_CNF          MSG_ID_SUPC_ABM_WIFI_DISCONNECT_CNF
#define MAP_MSG_ID_SUPC_ABM_WIFI_DISCONNECT_IND          MSG_ID_SUPC_ABM_WIFI_DISCONNECT_IND
#define MAP_MSG_ID_SUPC_ABM_WIFI_CONNECT_IND             MSG_ID_SUPC_ABM_WIFI_CONNECT_IND
#define MAP_MSG_ID_SUPC_ABM_WIFI_CONNECT_CNF             MSG_ID_SUPC_ABM_WIFI_CONNECT_CNF
#define MAP_MSG_ID_WNDRV_SUPC_PMKID_UPDATE_REQ           MSG_ID_WNDRV_SUPC_PMKID_UPDATE_REQ
#define MAP_MSG_ID_WNDRV_SUPC_DATA_REQ                   MSG_ID_WNDRV_SUPC_DATA_REQ
#define MAP_MSG_ID_WNDRV_SUPC_INIT_REQ                   MSG_ID_WNDRV_SUPC_INIT_REQ
#define MAP_MSG_ID_WNDRV_SUPC_AUTH_STATE_UPDATE_REQ      MSG_ID_WNDRV_SUPC_AUTH_STATE_UPDATE_REQ
#define MAP_MSG_ID_WNDRV_SUPC_BLACKLIST_UPDATE_REQ       MSG_ID_WNDRV_SUPC_BLACKLIST_UPDATE_REQ
#define MAP_MSG_ID_WNDRV_SUPC_DEINIT_REQ                 MSG_ID_WNDRV_SUPC_DEINIT_REQ
#define MAP_MSG_ID_WNDRV_SUPC_ADD_KEY_REQ                MSG_ID_WNDRV_SUPC_ADD_KEY_REQ
//#define MAP_MSG_ID_SUPC_MMI_WIFI_CURR_AP_INFO_IND        MSG_ID_SUPC_MMI_WIFI_CURR_AP_INFO_IND
#define MAP_MSG_ID_WNDRV_SUPC_QUERY_CAPABILITY_REQ       MSG_ID_WNDRV_SUPC_QUERY_CAPABILITY_REQ
#define MAP_MSG_ID_SUPC_ABM_WIFI_AP_LIST_CNF             MSG_ID_SUPC_ABM_WIFI_AP_LIST_CNF
#define MAP_MSG_ID_SUPC_ABM_WIFI_INIT_CNF                MSG_ID_SUPC_ABM_WIFI_INIT_CNF
#define MAP_MSG_ID_SUPC_ABM_WIFI_DEINIT_CNF              MSG_ID_SUPC_ABM_WIFI_DEINIT_CNF
//#define MAP_MSG_ID_SIM_READ_REQ                          MSG_ID_SIM_READ_REQ
#define MAP_MSG_ID_WNDRV_SUPC_JOIN_NETWORK_REQ           MSG_ID_WNDRV_SUPC_JOIN_NETWORK_REQ
#define MAP_MSG_ID_WNDRV_SUPC_DISJOIN_NETWORK_REQ        MSG_ID_WNDRV_SUPC_DISJOIN_NETWORK_REQ
#define MAP_MSG_ID_WNDRV_SUPC_SITE_SURVEY_REQ            MSG_ID_WNDRV_SUPC_SITE_SURVEY_REQ
#define MAP_MSG_ID_WNDRV_SUPC_CHIP_POWERON_REQ           MSG_ID_WNDRV_SUPC_CHIP_POWERON_REQ
#define MAP_MSG_ID_WNDRV_SUPC_CHIP_POWEROFF_REQ          MSG_ID_WNDRV_SUPC_CHIP_POWEROFF_REQ
#define MAP_MSG_ID_WNDRV_SUPC_REMOVE_KEY_REQ             MSG_ID_WNDRV_SUPC_REMOVE_KEY_REQ
#define MAP_MSG_ID_SUPC_ABM_WIFI_WPS_INFO_IND            MSG_ID_SUPC_ABM_WIFI_WPS_INFO_IND


#define MAP_MOD_SUPC     MOD_SUPC
#define MAP_MOD_ABM      MOD_ABM
#define MAP_MOD_WNDRV    MOD_WNDRV
#define MAP_MOD_MMI      MOD_MMI
//#define MAP_MOD_SIM      MOD_SIM
#define MAP_MOD_TIMER    MOD_TIMER

#define MAP_SUPC_ABM_SAP     SUPC_ABM_SAP
#define MAP_WNDRV_SUPC_SAP   WNDRV_SUPC_SAP
#define MAP_SUPC_MMI_SAP     SUPC_MMI_SAP
//#define MAP_PS_SIM_SAP       PS_SIM_SAP
#endif /*__SUPC_MAP_H__*/

