/*
 * Generated by MTK Easy PinMux Tool Version 2.4.0 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2018-04-13 17:16:45:0399
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
