/* Copyright Statement:
 *
 * (C) 2005-2016  MediaTek Inc. All rights reserved.
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. ("MediaTek") and/or its licensors.
 * Without the prior written permission of MediaTek and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) MediaTek Software
 * if you have agreed to and been bound by the applicable license agreement with
 * MediaTek ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of MediaTek Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT MEDIATEK SOFTWARE RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

#ifndef _WNDRV_TRC_H
#define _WNDRV_TRC_H

//#include "stack_config.h"
#include "kal_trace.h"


#define TRACE_SCAN      TRACE_GROUP_1

#define TRACE_CONN      TRACE_GROUP_2
#define TRACE_DISCONN   TRACE_GROUP_2

#define TRACE_SEARCH    TRACE_GROUP_3
#define TRACE_ROAMING   TRACE_GROUP_3

#define TRACE_TXRX      TRACE_GROUP_4

#define TRACE_HOTSPOT   TRACE_GROUP_5

#define TRACE_P2P       TRACE_GROUP_6
#define TRACE_WAPI      TRACE_GROUP_6

#define TRACE_INIT      TRACE_GROUP_7
#define TRACE_DEINIT    TRACE_GROUP_7


#define wndrvPrintf         printc

extern kal_uint32 wndrv_dbglevel;

#if 0
#define kal_trace(tst_lev,...)                          \
            do{                                         \
                if((1 << tst_lev) & wndrv_dbglevel){    \
                    wndrvPrintf("[WNDRV ] "__VA_ARGS__);wndrvPrintf("\n"); \
                }                                       \
            }while(0)

#define kal_wap_trace(tst_id, tst_lev,...)                  \
    do{                                                     \
        if((1 << tst_lev) & wndrv_dbglevel){                \
            wndrvPrintf("[WNDRV ] "__VA_ARGS__);wndrvPrintf("\n"); \
        }                                                   \
    }while(0)

#define MT5931_NEW_TRACE(tst_id, tst_lev, str, ...)         \
        do{                                                 \
            if((1 << tst_lev) & wndrv_dbglevel){            \
                wndrvPrintf("[WNDRV ] "str"\n",__VA_ARGS__); \
            }                                               \
        }while(0)

#define MT5931_NEW_TRACE0(tst_id, tst_lev, str)             \
        do{                                                 \
            if((1 << tst_lev) & wndrv_dbglevel){            \
                wndrvPrintf("[WNDRV ] "str"\n");            \
            }                                               \
        }while(0)


#define MT5931_TRACE(tst_lev, tst_id, str, ...)             \
        do{                                                 \
            if((1 << tst_lev) & wndrv_dbglevel){            \
                wndrvPrintf("[WNDRV ] "str"\n",__VA_ARGS__); \
            }                                               \
        }while(0)


#define MT5931_TRACE0(tst_lev, tst_id, str)                 \
        do{                                                 \
            if((1 << tst_lev) & wndrv_dbglevel){            \
                wndrvPrintf("[WNDRV ] "str"\n");                \
            }                                               \
        }while(0)
#else

#define kal_trace(tst_lev,...)                                  \
            do{                                                 \
                if((1 << tst_lev) & wndrv_dbglevel){            \
                    if((tst_lev == TRACE_ERROR) || (tst_lev == TRACE_WARNING)){ \
                        wndrvPrintf(RED_ON"[WNDRV ] "__VA_ARGS__);wndrvPrintf("\n"RED_OFF); \
                    }else{                                      \
                        wndrvPrintf("[WNDRV ] "__VA_ARGS__);wndrvPrintf("\n"); \
                    }                                           \
                }                                               \
            }while(0)

#define kal_wap_trace(tst_id, tst_lev,...)                      \
        do{                                                     \
            if((1 << tst_lev) & wndrv_dbglevel){                \
                if((tst_lev == TRACE_ERROR) || (tst_lev == TRACE_WARNING)){ \
                    wndrvPrintf(RED_ON"[WNDRV ] "__VA_ARGS__);wndrvPrintf("\n"RED_OFF); \
                }else{                                          \
                    wndrvPrintf("[WNDRV ] "__VA_ARGS__);wndrvPrintf("\n"); \
                }                                               \
            }                                                   \
        }while(0)

#define MT5931_NEW_TRACE(tst_id, tst_lev, str, ...)             \
        do{                                                     \
            if((1 << tst_lev) & wndrv_dbglevel){                \
                if((tst_lev == TRACE_ERROR) || (tst_lev == TRACE_WARNING)){ \
                    wndrvPrintf(RED_ON"[WNDRV ] "str"\n"RED_OFF,__VA_ARGS__);\
                }else{                                          \
                    wndrvPrintf("[WNDRV ] "str"\n",__VA_ARGS__); \
                }                                               \
            }                                                   \
        }while(0)

#define MT5931_NEW_TRACE0(tst_id, tst_lev, str)                 \
        do{                                                     \
            if((1 << tst_lev) & wndrv_dbglevel){                \
                if((tst_lev == TRACE_ERROR) || (tst_lev == TRACE_WARNING)){ \
                    wndrvPrintf(RED_ON"[WNDRV ] "str"\n"RED_OFF);\
                }else{                                          \
                    wndrvPrintf("[WNDRV ] "str"\n");            \
                }                                               \
            }                                                   \
        }while(0)


#define MT5931_TRACE(tst_lev, tst_id, str, ...)                 \
        do{                                                     \
            if((1 << tst_lev) & wndrv_dbglevel){                \
                if((tst_lev == TRACE_ERROR) || (tst_lev == TRACE_WARNING)){ \
                    wndrvPrintf(RED_ON"[WNDRV ] "str"\n"RED_OFF,__VA_ARGS__);\
                }else{                                          \
                    wndrvPrintf("[WNDRV ] "str"\n",__VA_ARGS__); \
                }                                               \
            }                                                   \
        }while(0)


#define MT5931_TRACE0(tst_lev, tst_id, str)                     \
        do{                                                     \
            if((1 << tst_lev) & wndrv_dbglevel){                \
                if((tst_lev == TRACE_ERROR) || (tst_lev == TRACE_WARNING)){\
                    wndrvPrintf(RED_ON"[WNDRV ] "str"\n"RED_OFF);\
                }else{                                          \
                    wndrvPrintf("[WNDRV ] "str"\n");                \
                }                                               \
            }                                                   \
        }while(0)

#endif

#define WNDRV_TRACE         kal_trace

#define MT5931_WAP_TRACE    kal_wap_trace

#define DEBUGFUNC(_Func) MT5931_WAP_TRACE(MOD_WNDRV, TRACE_FUNC, _Func);


#define   INFO_WNDRV_SHOW_REG    "[WIFI] regulation domain: %d"
#define   INFO_WNDRV_SHOW_MAC_STATE    "[WIFI] MAC_State: %d"
#define   INFO_WNDRV_SHOW_RADIO_STATE    "[WIFI] Radio_State: %d, %d"
#define   INFO_WNDRV_SHOW_PS_STATE    "[WIFI] PS_State: %d, %d, %d, %d"
#define   INFO_WNDRV_SHOW_MESSAGE_SIZE    "[WIFI] MessageSize: %d, %d, %d, %d"
#define   INFO_WNDRV_SHOW_TX_RX_QUEUE_SIZE    "[WIFI] TXQueueNumSize: %d, %d, %d, %d, %d, %d, %d"
#define   INFO_WNDRV_SHOW_TX_EX_QUEUE_SIZE    "[WIFI] TXQueueEXSize: %d, %d, %d, %d"
#define   INFO_WNDRV_SHOW_RSSI_SQ    "[WIFI] RSSI_SQ: %d %d"
#define   INFO_WNDRV_SHOW_RATE    "[WIFI] RATE: %d"
#define   INFO_WNDRV_LASTBSSFRAMERXTIME    "[WIFI] LastBSSFrameRXTime: %d"

//20081128 add by saker
#define   INFO_WNDRV_ARB_STATE_TRANS    "ARB TRANSITION: [%MENUM_ARB_STATE_T] -> [%MENUM_ARB_STATE_T]"
#define   INFO_WNDRV_JOIN_STATE_TRANS    "JOIN TRANSITION: [%MENUM_JOIN_STATE_T] -> [%MENUM_JOIN_STATE_T]"
#define   INFO_WNDRV_ROAM_STATE_TRANS    "ROAM TRANSITION: [%MENUM_ROAMING_STATE_T] -> [%MENUM_ROAMING_STATE_T]"
#define   INFO_WNDRV_SCAN_STATE_TRANS    "SCAN TRANSITION: [%MENUM_SCAN_STATE_T] -> [%MENUM_SCAN_STATE_T]"
#define   INFO_WNDRV_SEC_STATE_TRANS    "SEC TRANSITION: [%MENUM_SEC_STATE_T] -> [%MENUM_SEC_STATE_T]"

/* ----------------- TRACE_INFO trace class ------------------- */
#define   INFO_ADD_RECORD_FOR_STA                  "Add record for STA [%02x-%02x-%02x-%02x-%02x-%02x], RecordCount=%d"
#define   INFO_REMOVE_RECORD_FOR_STA               "Remove record for STA [%02x-%02x-%02x-%02x-%02x-%02x], RecordCount=%d"
#define   INFO_CHECK_BSS_TKIP_COUNTERMEASURES      "Under TKIP countermeasures"
#define   INFO_CHECK_BSS_FAILURE_PREVIOUS_REQ      "Failure of previous request %d"
#define   INFO_CHECK_BSS_AD_HOC_MISMATCH           "BSSType not matched (ad hoc required)"
#define   INFO_CHECK_BSS_SSID_MISMATCH             "Desired SSID not matched %d Co:%d"
#define   INFO_CHECK_BSS_INFRASTRUCTURE_MISMATCH    "BSSType not matched (infrastructure required)"
#define   INFO_CHECK_BSS_PROTECTED_BSS             "Protected BSS"
#define   INFO_CHECK_BSS_NON_WPA2_BSS              "Non-WPA2 BSS, RSN IE not present"
#define   INFO_CHECK_BSS_RSN_POLICY_FAIL           "Policy selection fail for RSN IE"
#define   INFO_CHECK_BSS_NON_WPA_BSS               "Non-WPA BSS, WPA IE not present"
#define   INFO_CHECK_BSS_WPA_POLICY_FAIL           "Policy selection fail for WPA IE"
#define   INFO_CHECK_BSS_WEP_ONLY                  "WEP-only legacy BSS"
#define   INFO_CHECK_BSS_UNPROTECTED_BSS_1         "Unprotected BSS (1)"
#define   INFO_CHECK_BSS_UNPROTECTED_BSS_2         "Unprotected BSS (2)"
#define   INFO_CHECK_BSS_UNKNOWN_BSS_BASIC_RATE    "Unknown BSS basic rate(s)"
#define   INFO_CHECK_BSS_IBSS_LONG_SLOT            "IBSS with long slot time"
#define   INFO_CHECK_BSS_IBSS_SHORT_SLOT           "IBSS with short slot time"
#define   INFO_CHECK_BSS_NOT_11G_IBSS              "Not 11g IBSS"
#define   INFO_CHECK_BSS_NOT_SUPPORT_BASIC_RATE    "Not fully support basic rate, BSSBasicRateSet = 0x%08x, supportedRateSetRx = 0x%08x"
#define   INFO_CHECK_BSS_NOT_SUPPORT_DESIRED_RATE    "Desired rate not supported, BSSOperationalRateSet = 0x%08x, desiredRateSet = 0x%08x"

/* ----------------- TRACE_WARNING trace class ---------------- */
#define   WARNING_DECRYPT_NULL_KEY_ENTRY    "MPDU decapsulation with null key entry"
#define   WARNING_DECRYPT_INVALID_CIPHER    "Error, MPDU decapsulation with invalid cipher: %d (G)"
#define   WARNING_TX_SETUP_BSS_RATES       "No lowest BSS basic rate"
#define   WARNING_NO_BASIC_RATE_FOR_MC_BC    "No basic rate for mc/bc. Use rate 0x%02x instead"
#define   WARNING_NO_RATE_TO_TRANSMIT      "No rate to transmit. Use 1M instead"
#define   WARNING_NO_BASIC_RATE_FOR_BEACON    "No BSS basic rates for beacon. Use 1M instead"
#define   WARNING_NO_RA_RECORD             "No RA record. Use rate 0x%02x instead"
#define   WARNING_WLAN_SEND_PACKET         "Fail send with flags 0x%08x"
#define   WARNING_FORCE_TO_IDLE_STATE      "There should be no such state. MAC_STATE: %d, LINE: %d"
#define   WARNING_NO_FLC_BUFFER            "Cannot allocate flow control buffer"
#define   WARNING_NO_BUFFER_FOR_SCAN       "No buffer for new scan result"
#define   WARNING_NO_BUFFER_FOR_PS_POLL_FRAME    "No buffer for PS-Poll frame"
#define   WARNING_NO_BUFFER_FOR_ACTION_FRAME    "No buffer for Action frame"
#define   WARNING_NO_BUFFER_FOR_ASSOC_FRAME     "No buffer for (Re)Assoc Req frame"
#define   WARNING_NO_BUFFER_FOR_DISASSOC_FRAME    "No buffer for Disassoc frame"
#define   WARNING_NO_BUFFER_FOR_AUTH_SEQ_1_FRAME    "No buffer for Auth seq 1 frame"
#define   WARNING_NO_BUFFER_FOR_AUTH_SEQ_2_FRAME    "No buffer for Auth seq 2 frame"
#define   WARNING_NO_BUFFER_FOR_AUTH_SEQ_3_FRAME    "No buffer for Auth seq 3 frame"
#define   WARNING_NO_BUFFER_FOR_AUTH_SEQ_4_FRAME    "No buffer for Auth seq 4 frame"
#define   WARNING_NO_BUFFER_FOR_DEAUTH_FRAME      "No buffer for Deauth frame"
#define   WARNING_NO_BUFFER_FOR_IAPP_FRAME        "No buffer for IAPP frame"
#define   WARNING_NO_BUFFER_FOR_NULL_FRAME       "No buffer for Null frame"
#define   WARNING_NO_BUFFER_FOR_PROBE_RSP_FRAME    "No buffer for Probe Rsp frame"
#define   WARNING_UFIFO_CHECKSUM_ERROR     "Ufifo checksum error  MCR_UFFS =0x%08x"
#define   WARNING_RESET_MAC                "Reset MAC ****************"
#define   WARNING_NO_SLAB_MEMORY           "No appropriate slab mamory anchor_p->alloc_count=%d, desiredMemSz=%d"
#define   WARNING_NO_FREE_STA_RECORD       "No free STA record for [%02x-%02x-%02x-%02x-%02x-%02x]"
#define   WARNING_NO_STA_RECORD_FOR_STATE3    "No record for STA [%02x-%02x-%02x-%02x-%02x-%02x] with new state 3"
#define   WARNING_OLD_FRAGMENT_TIMEOUT     "Old fragments timeout (rx fragments queue [%d])"
#define   WARNING_UNKNOWN_FRAGMENT         "Unknown fragment (Seq_Ctrl=0x%04x)"
#define   WARNING_FRAGMENTS_TIMEOUT        "Fragments timeout (Seq_Ctrl=0x%04x)"
#define   WARNING_RSN_IE_TOO_SHORT         "RSN IE length too short (length=%d)"
#define   WARNING_UNSUPPORTED_RSN_IE_VERSION    "Unsupported RSN IE version: %d"
#define   WARNING_FAIL_PARSE_RSN_IE           "Fail to parse RSN IE (IE len: %d)(line: %d)"
#define   WARNING_WPA_IE_TOO_SHORT            "WPA IE length too short (length=%d)"
#define   WARNING_UNSUPPORTED_WPA_IE_VERSION    "Unsupported WPA IE version: %d"
#define   WARNING_FAIL_PARSE_WPA_IE           "Fail to parse WPA IE (IE len: %d)(line: %d)"
#define   WARNING_MP_IS_NOT_READY          "Halt/remove/surprised removed/reset in progress 0x%x"
#define   WARNING_ACTION_UNRECOGNIZED_FIELD    "Unrecognized category field %d"
#define   WARNING_MGT_STATE_TIMEOUT           "There should be no such state. :%d %d"
#define   WARNING_NOT_ASSOCIATED_WITH_WSM_AP    "Not associated with a WSM AP"
#define   WARNING_CHECK_DTIMLAG               "tsfComputeDtimLag-period is zero %d %d"
#define   WARNING_NO_RX_OK_BUT_LPINT_C    "No Rx OK but LPInt_C!!!"
#define   WARNING_NO_RX_OK_BUT_LPINT_D    "No Rx OK but LPInt_D!!!"
#define   WARNING_NO_RX_OK_BUT_LPINT_E    "No Rx OK but LPInt_E!!!"
#define   WARNING_TKIP_MIC_ERROR                "Error, TKIP MIC error (P)!"
#define   WARNING_BBCR24_RATE_INVALID    "BBCR24 Rate Invalid %d"
#define   WARNING_MCR_WRITE_FAIL    "Failed to write Beacon Content. MCR: %x, regValue: %x"
#define   WARNING_MCR_READ_FAIL    "Cannot write BC due to busy BC access. MCR: %x, regValue: %x"
#define   WARNING_NO_WIFI_BEARAR       "No WiFi bearer"
#define   WARNING_INVALID_AC_PARAMETERS_BE    "Invalid AC Parameters BE"
#define   WARNING_INVALID_AC_PARAMETERS_BK    "Invalid AC Parameters BK"
#define   WARNING_INVALID_AC_PARAMETERS_VI    "Invalid AC Parameters VI"
#define   WARNING_INVALID_AC_PARAMETERS_VO    "Invalid AC Parameters VO"
#define   WARNING_FAIL_GET_WME_PARAMETERS     "Failed to get WME parameters from (Re)Assoc Req"
#define   WARNING_PARSE_TOTAL_LEN_NOT_EQUAL        "Total Len is not equal %d %d"
#define   WARNING_PARSE_HUGE_IE_LEN                "Huge IELength = %d BSSID = [%02x-%02x-%02x-%02x-%02x-%02x]"
#define   WARNING_PARSE_TOTAL_IE_LEN_NOT_EQUAL     "Total Len %d is different from sum of IE length %d, BSSID = [%02x-%02x-%02x-%02x-%02x-%02x]"
#define   WARNING_PARSE_UNREASONABLE_BUFFER_LEN    "Unreasonable buffer len: %d"
#define   WARNING_PARSE_UNREASONABLE_IE_LEN        "Unresonable vendor IE: %d length:%d"
#define   WARNING_PARSE_UNREASONABLE_IE_LEN_2      "Unresonable vendor IE: %d length:%d, maxLen:%d"
#define   WARNING_PARSE_UNREASONABLE_WFA_IE_LEN    "Unreasonable WFA IE len: %d maxLen:%d"
#define   WARNING_ABNORMAL_NEXT_TBTT_TIME          "Abnormal nextTBTTTime: %d, Target: %d, SleepPeriod: %d, BeaconPeriod: %d, DtimPeriod: %d"

//20081127 add by saker
#define   WARNING_ARB_SCAN_BLOCK    "Scan is blocked for over %d ms"
#define   WARNING_NIC_TX_MPDU_RETRY_ERR    "MPDU Retry Error"
#define   WARNING_ASSOC_ALLOC_FAIL    "No MSDU_INFO_T to send (Re)Association Request"
#define   WARNING_DISASSOC_ALLOC_FAIL    "No MSDU_INFO_T to send Disassociation frame"
#define   WARNING_AUTH_ALLOC_FAIL    "No MSDU_INFO_T to send Auth Request"
#define   WARNING_DEAUTH_ALLOC_FAIL    "No MSDU_INFO_T to send Deauth Request"
#define   WARNING_PROBE_RESP_ALLOC_FAIL    "No MSDU_INFO_T to send Probe Response"
#define   WARNING_ASSOC_INV_AID    "Invalid AID: %d"
#define   WARNING_JOIN_UNKNOW_BSS_RATE    "BSS has unknown BSS Basic Rate: Operational Rate Set = %d, BSS Basic Rate Set = %d"
#define   WARNING_NO_BUFFER_FOR_AUTH_REQ_FRAME    "No buffer for Auth req frame"
#define   WARNING_NO_BUFFER_FOR_PROBE_REQ_FRAME    "No buffer for Probe Req frame"
#define   WARNING_TX_WRITE_FRAME_FAIL    "Write TX frame fail"
#define   WARNING_RSN_TOO_SHORT    "RSN IE length too short (length=%d)"
#define   WARNING_RSN_GROUP_PARSE_FAIL    "Fail to parse RSN IE in group cipher suite (IE len: %d)"
#define   WARNING_RSN_PAIR_PARSE_FAIL    "Fail to parse RSN IE in pairwise cipher suite count (IE len: %d)"
#define   WARNING_RSN_TKIP_NO_KEY    "Received packet can't got key to decrypting!"
#define   WARNING_ARB_PREV_STATE    "ARB prevState: %d"
#define   WARNING_ARB_RESET_STATE    "Try to reset in state %d"
#define   WARNING_HAL_ENTRY_NOSUPPORT    "Not support this entry index"
#define   WARNING_RSN_ENTRY_INDEX    "Wlan table index %d"
#define   WARNING_NIC_NOTAVA_ENTRY    "No available wlan table entry"
#define   WARNING_RSN_UNKNOWN_CIPHER_MODE    "Unknown Cipher mode %d"
#define   WARNING_RSN_DROP_RCV_NONENCRYPT    "Drop rcv non-encrypted data frame"
#define   WARNING_WNDRV_PM_CANNOT_CHANGE_PM_STATE_AT_ONCE    "Cannot change PM state at once !!"
#define   WARNING_WNDRV_INIT_FAIL    "Init fail with status code: %d"

/* ----------------- TRACE_ERROR trace class ------------------ */
#define   ERROR_CALCULATE_RSSI        "CR29_LNA Strange 0x%08x"
#define   ERROR_CHECK_CHIP_ID_VERSION    "Unsupported chip ID & version: PCICR=0x%08x"
#define   ERROR_CHECK_BUS_INTERFACE_1    "MCR_OMAR0=%x, MCR_OMAR1=%x"
#define   ERROR_CHECK_BUS_INTERFACE_2    "MCR_OMAR0=%x, MCR_OMAR1=%x"
#define   ERROR_RX_DATA_BYTE_COUNT     "rxDataByteCount = %x is not mutiple of 4"
#define   ERROR_RX_INVALID_LENGTH      "hwRfb_p->rxDataByteCount=%d"
#define   ERROR_RX_INVALID_LENGTH_2    "hwRfb_p->rxByteCount=%d"
#define   ERROR_RX_INVALID_RESERVED_0    "Error on hwRfb_p->reserved0, hwRfb_p->reserved0=%x"
#define   ERROR_RX_INVALID_RX_STATUS    "Error on hwRfb_p->rxStatus, hwRfb_p->rxStatus=%x"
#define   ERROR_RX_INVALID_SEC_STATUS    "Error on hwRfb_p->secStatus, hwRfb_p->secStatus=%x"
#define   ERROR_RX_INVALID_BBCR_D      "Error on hwRfb_p->bbCrD, hwRfb_p->bbCrD=%x"
#define   ERROR_RX_FCS_ERROR           "FCS error!, 0x%08x"
#define   ERROR_RX_SEQ_NO_ERROR        "Rx Seq No are different: status:%02x, packet:%02x"
#define   ERROR_RX_DONE_FALSE_ALARM    "Rx done interrupt false alarm, rxStatus: %08x"
#define   ERROR_RX_UNEXPECTED_FRAME    "Unexpected frame (frame type = %04x)"
#define   ERROR_RX_INVALID_PS_POLL_FRAME    "Invalid PS-Poll frame of length %d"

//20081127 add by saker
#define   ERROR_INIT_READCONFIG    "nicReadConfig Error!"
#define   ERROR_INIT_ALLOCMEM    "nicAllocateAdapterMemory Error!"
#define   ERROR_ARB_RFTEST_INIT_FAIL    "Rf Test Init fail"
#define   ERROR_ARB_PARTIAL_SCAN_FAIL    "Unable to perform next PARTIAL SCAN request"
#define   ERROR_JOIN_REENTRY    "Reentry of JOIN Module - JOIN_STATE is not in IDLE_STATE"
#define   ERROR_JOIN_BSS_NOT_SUPPORT    "Target BSS Type : %d is not supported by JOIN"
#define   ERROR_JOIN_AUTH_NOT_SUPPORT    "Authentication Algorithm : %d was not supported by JOIN"
//20090114 add by lcko
#define   ERROR_RX_STATUS_IS_FCS_ERROR    "RX_STATUS_IS_FCS_ERROR"
#define   ERROR_RX_STATUS_IS_ICV_ERROR    "RX_STATUS_IS_ICV_ERROR"
#define   ERROR_RX_STATUS_IS_KEY_ERROR    "RX_STATUS_IS_KEY_ERROR"
#define   ERROR_RX_STATUS_IS_FORMAT_ERROR    "RX_STATUS_IS_FORMAT_ERROR"

/* --------------TRACE_GROUP_1 trace class (Connection)---------------------------- */
#define   INFO_WNDRV_SCAN_ON_GOING              "SCAN_ON_GOING:......scan:%d"
#define   INFO_WNDRV_SCAN_GOING_TO_STOP         "SCAN_TO_STOP: Going to stop scan..."
#define   INFO_WNDRV_SCAN_REQUEST_START         "SCAN_REQUEST_START: currentTime=%d"
#define   INFO_WNDRV_SCAN_NEXT_CHANNEL          "SCAN_NEXT_CHANNEL: scanType=%d, minChannelTime=%d, maxChannelTime=%d, channel=%d, currentTime=%d"
#define   INFO_WNDRV_SCAN_REQUEST_COMPLETE      "SCAN_REQUEST_COMPLETE: scanResultCount=%d, currentTime=%d"
#define   INFO_WNDRV_JOIN_START_IBSS            "INFO_JOIN_START_IBSS: channel=%d, beaconInterval=%d"
#define   INFO_WNDRV_JOIN_NO_BSS                "JOIN_NO_BSS: **********************"
#define   INFO_WNDRV_JOIN_DESIRED_BSS           "JOIN_DESIRED_BSS: Attempt to join the BSS [%02x-%02x-%02x-%02x-%02x-%02x]"
#define   INFO_WNDRV_CONNECT_RETRY_FAIL         "CONNECT_RETRY_FAIL: Connection retry fail =  %d times"
#define   INFO_WNDRV_AUTH_ON_GOING              "AUTH_ON_GOING:......Authentication request on going"
#define   INFO_WNDRV_AUTH_SEND_SEQ_1            "AUTH_FRAME: Send Auth seq 1 frame"
#define   INFO_WNDRV_AUTH_SEND_SEQ_3            "AUTH_FRAME: Send Auth seq 3 frame"
#define   INFO_WNDRV_AUTH_REFUSE                "Authentication request: REFUSED (status code=%d)"
#define   INFO_WNDRV_AUTH_RX_DEAUTH             "Deauthenticate: requester=[%02x-%02x-%02x-%02x-%02x-%02x], reason code=%d"
#define   INFO_WNDRV_AUTH_TIMEOUT               "Authentication request: TIMEOUT"
#define   INFO_WNDRV_AUTH_TIMEOUT_AND_RETRY     "Authentication request timeout and retry = %d"
#define   INFO_WNDRV_AUTH_FAIL                  "Authenticate fail: statusCode = %d"
#define   INFO_WNDRV_ASSOC_ON_GOING             "Association request:(Re)association request on going..."
#define   INFO_WNDRV_ASSOC_SEND_SEQ             "Send (Re)Assoc Req frame"
#define   INFO_WNDRV_ASSOC_SUCCESS              "Association request: SUCCESS (AID = %d)"
#define   INFO_WNDRV_ASSOC_REFUSED              "Association request: REFUSED (status code = %d)"
#define   INFO_WNDRV_ASSOC_RX_DISASSOC          "Disassociate: requester = %02x-%02x-%02x-%02x-%02x-%02x, reason code = %d"
#define   INFO_WNDRV_ASSOC_TIMEOUT              "Associate request: TIMEOUT"
#define   INFO_WNDRV_ASSOC_TIMEOUT_AND_RETRY    "Associate request timeout and retry = %d"
#define   INFO_WNDRV_ASSOC_FAIL                 "Associate fail: statusCode = %d"
#define   INFO_WNDRV_CANCEL_ON_LINE_SITESURVEY    "Failed to send Null frame -- Cancel on-line site survey"
#define   INFO_WNDRV_SCAN_ASSOC_TIMEOUT         "Start the management request timer for the (re)association procedure after scanning"
#define   INFO_WNDRV_SCAN_RESULT_NOT_FOUND      "There is no suitable candidate in %d scan result(s)"
#define   INFO_WNDRV_RX_DEAUTH_AND_RETRY        "RX deauthentication and re-connect"
#define   INFO_WNDRV_RX_DEAUTH_PTA_SCORE        "SelfPTAOnScore = %d"
#define   INFO_WNDRV_SWITCH_PTA                 "SelfPTAOnScore = %d, Threshold = %d, Turn on PTA= %d"
#define   INFO_WNDRV_CONNECT_TOO_MANY_AP        "There are %d other APs in the same channel !!"
#define   INFO_WNDRV_LCD_OFF_TO_ON              "LCD from OFF to ON !!"
#define   INFO_WNDRV_EXTEND_AUTH_ASSOC_TIMEOUT    "Extend the timeout of authenticate and associate"

//20081128 add by saker
#define   INFO_WNDRV_AUTH_REJECT    "Auth Req was rejected by [%02x-%02x-%02x-%02x-%02x-%02x], Status Code = %d"
#define   INFO_WNDRV_ASSOC_REJECT    "Assoc Req was rejected by [%02x-%02x-%02x-%02x-%02x-%02x], Status Code = %d"
#define   INFO_WNDRV_JOIN_COMPLETE    "JOIN to BSSID: [%02x-%02x-%02x-%02x-%02x-%02x]"


/* --------------TRACE_GROUP_2 trace class (Timer)--------------------------------- */
#define   INFO_WNDRV_KAL_GET_TICK             "WKAL: GetTick=%d"
#define   INFO_WNDRV_KAL_U_DELAY              "WKAL: Udelay=%d"
#define   INFO_WNDRV_KAL_M_DELAY              "WKAL: Mdelay=%d"
#define   INFO_WNDRV_KAL_STOP_TIMER           "WKAL: StopTimer"
#define   INFO_WNDRV_KAL_SET_TIMER            "WKAL: SetTimer=%d"


/* --------------TRACE_GROUP_3 trace class (SUPC function interface)----- */

#define   INFO_WNDRV_SUPC_INIT_REQ              "SUPC_INIT_REQ: *****************"
#define   INFO_WNDRV_SUPC_DEINIT_REQ            "SUPC_DEINIT_REQ: ***************"
#define   INFO_WNDRV_SUPC_SITE_SURVEY_REQ       "SUPC_SITE_SURVEY_REQ: **********"
#define   INFO_WNDRV_SUPC_JOIN_NETWORK_REQ      "SUPC_JOIN_NETWORK_REQ: *********"
#define   INFO_WNDRV_SUPC_DISJOIN_NETWORK_REQ    "SUPC_DISJOIN_NETWORK_REQ: ******"
#define   INFO_WNDRV_SUPC_DATA_REQ              "SUPC_DATA_REQ: *****************"
#define   INFO_WNDRV_SUPC_ADD_KEY_REQ           "SUPC_ADD_KEY_REQ: **************"
#define   INFO_WNDRV_SUPC_REMOVE_KEY_REQ        "SUPC_REMOVE_KEY_REQ: ***********"
#define   INFO_WNDRV_SUPC_PMKID_UPDATE_REQ      "PMKID_UPDATE_REQ: **************"
#define   INFO_WNDRV_SUPC_COUNTRY_SETTING_REQ    "COUNTRY_SETTING_REQ: ***********"

#define   INFO_WNDRV_TCPIP_DATA_REQ             "TCPIP_DATA_REQ: ****************"


/* --------------TRACE_GROUP_4 trace class (Memory, Reg or Data Port Read/Write)----------- */
#define   INFO_WNDRV_KAL_IND_STATUS_COMPLETE    "WKAL: IndStatusAndComplete"
#define   INFO_WNDRV_KAL_PKT_GET_INFO         "WKAL: PktGetInfo: pdu_len=%d"
#define   INFO_WNDRV_KAL_SEND_COMPLETE_SYS    "WKAL: SendComplete: tx_sys_peer_num=%d"
#define   INFO_WNDRV_KAL_SEND_COMPLETE_FLC    "WKAL: SendComplete: tx_flc_peer_num=%d"
#define   INFO_WNDRV_KAL_MBUF_GET_INFO        "WKAL: MbufGetInfo: pdu_len=%d"
#define   INFO_WNDRV_KAL_MBUF_GET_NEXT        "WKAL: MbufGetNext"
#define   INFO_WNDRV_KAL_PKT_ALLOC_SYS        "WKAL: PacketAlloc: rx_sys_peer_num=%d, pdu_len=%d"
#define   INFO_WNDRV_KAL_PKT_ALLOC_FLC        "WKAL: PacketAlloc: rx_flc_peer_num=%d, pdu_len=%d"
#define   INFO_WNDRV_KAL_PKT_FREE_SYS         "WKAL: PacketFree: rx_sys_peer_num=%d"
#define   INFO_WNDRV_KAL_PKT_FREE_FLC         "WKAL: PacketFree: rx_flc_peer_num=%d"
#define   INFO_WNDRV_KAL_PKT_PUT              "WKAL: PacketPut"
#define   INFO_WNDRV_KAL_IND_PACKETS_SYS      "WKAL: IndPackets: rx_sys_peer_num=%d"
#define   INFO_WNDRV_KAL_IND_PACKETS_FLC      "WKAL: IndPackets: rx_flc_peer_num=%d"
#define   INFO_WNDRV_KAL_MEM_ALLOC            "WKAL: Malloc: mem_size=%d"
#define   INFO_WNDRV_KAL_MEM_FREE             "WKAL: Mfree: mem_size=%d"
#define   INFO_WNDRV_KAL_DEV_REG32_READ       "WKAL: reg32_read=0x%x, val=0x%x, status=%d"
#define   INFO_WNDRV_KAL_DEV_REG32_WRITE      "WKAL: reg32_write=0x%x, val=0x%x, status=%d"
#define   INFO_WNDRV_KAL_DEV_REG16_READ       "WKAL: reg16_read=0x%x, val=0x%x, status=%d"
#define   INFO_WNDRV_KAL_DEV_REG16_WRITE      "WKAL: reg16_write=0x%x, val=0x%x, status=%d"
#define   INFO_WNDRV_KAL_SD_READ_PORT         "WKAL: port_read=0x%x, len=%d, status=%d"
#define   INFO_WNDRV_KAL_SD_WRITE_PORT        "WKAL: port_write=0x%x, len=%d, status=%d"
#define   INFO_WNDRV_DATA_PORT_RAW_DATA       "WKAL: 0x%x: %x"
#define   INFO_WNDRV_HISR_COUNT               "HISR: count: %d"
// 20090114 add by lcko
#define   INFO_WNDRV_PKT_DROP    "WKAL: prRxStatus->ucDropPacketNum = %d"
#define   INFO_WNDRV_NO_MORE_RFB    "WKAL: No More RFB"
#define   INFO_WNDRV_RD_RX_LEN_ERROR    "WKAL: Read RX LEN error"
#define   INFO_WNDRV_GET_0_HRDR    "WKAL: Get 0 from HRDR"
#define   INFO_WNDRV_RX_SIZE_LEN    "WKAL: RFB DW Size = %d, Packet Length = %d"
#define   INFO_WNDRV_RX_LEN_ERROR    "WKAL: Read RX Packet Lentgh Error (%d)"
#define   INFO_WNDRV_RFB_FAIL    "WKAL: halRxFillRFB failed"
// 20090215 add by lcko
#define   INFO_WNDRV_NO_MORE_FLC2    "WKAL: No More FLC2 Buffer"
#define   INFO_WNDRV_NO_MORE_FMSDU    "WKAL: No More Fragmented MSDU"
#define   INFO_WNDRV_MORE_FMSDU    "WKAL: More Fragmented MSDU"

/* --------------TRACE_GROUP_5 trace class (RFtest or inject message)------------------------------------ */
#define   INFO_WNDRV_SET_CHANNEL           "SET_CH: freq=%d"
#define   INFO_WNDRV_SET_TX_GAIN_DAC       "SET_GAIN: dac=%d"
#define   INFO_WNDRV_SET_RATE              "SET_RATE: %d"
#define   INFO_WNDRV_SET_STOP              "SET_STOP"
#define   INFO_WNDRV_SET_CONT_TX           "SET_CONT_TX: rate=%d"
#define   INFO_WNDRV_SET_LOCAL_FREQ        "SET_LOCAL_FREQ"
#define   INFO_WNDRV_SET_CARR_SUPP         "SET_CARR_SUPP"
#define   INFO_WNDRV_SET_PKT_TX            "SET_PKT_TX: len=%d, cnt=%d, inter=%d, pwr=%d, ant=%d, ptern=%d"
#define   INFO_WNDRV_SET_PWR_MGT           "SET_PWR_MGTt: %d"
#define   INFO_WNDRV_SET_PKT_RX            "PKT_RX: %d"
#define   INFO_WNDRV_SET_REG_DOMAIN        "SET_REG_DOMAIN: %c%c"
#define   INFO_WNDRV_SET_DBM2DAC           "SET_DBM2DAC: freq=%d, rate=%d, dbm=%d"
#define   INFO_WNDRV_SET_MCR32             "SET_MCR32: idx=0x%x, data=0x%x"
#define   INFO_WNDRV_SET_MCR16             "SET_MCR16: idx=0x%x, data=0x%x"
#define   INFO_WNDRV_SET_BBCR              "SET_BBCR: idx=%d, data=0x%x"
#define   INFO_WNDRV_SET_EEPROM            "SET_EEPROM: idx=0x%x, data=0x%x"
#define   INFO_WNDRV_QUERY_PKT_TX          "QUERY_PKT_TX: total=%d, acked=%d"
#define   INFO_WNDRV_QUERY_PKT_RX          "QUERY_PKT_RX: INT: ok=%d, crcErr=%d, short=%d, long=%d. PAU: num=%d, crcErr=%d, fifoFull=%d, cca=%d"
#define   INFO_WNDRV_QUERY_CH_ID_LIST      "QUERY_CH_ID_LIST: num=%d"
#define   INFO_WNDRV_QUERY_RX_COUNTER      "QUERY_RX_COUNTER"
#define   INFO_WNDRV_QUERY_DBM2DAC         "QUERY_DBM2DAC: dac=%d"
#define   INFO_WNDRV_QUERY_MCR32           "QUERY_MCR32: idx=0x%x, data=0x%x"
#define   INFO_WNDRV_QUERY_MCR16           "QUERY_MCR16: idx=0x%x, data=0x%x"
#define   INFO_WNDRV_QUERY_BBCR            "QUERY_BBCR: idx=%d, data=0x%x"
#define   INFO_WNDRV_QUERY_EEPROM          "QUERY_EEPROM: idx=0x%x, data=0x%x"
#define   INFO_WNDRV_SET_BEGIN             "SET_BEGIN: ****************"
#define   INFO_WNDRV_SET_END               "SET_END: successful=%d ******"
#define   INFO_WNDRV_QUERY_BEGIN           "QUERY_BEGIN: ****************"
#define   INFO_WNDRV_QUERY_END             "QUERY_END: ****************"

/* --------------TRACE_GROUP_6 trace class (Low Power)----------------------------- */
#define   INFO_WNDRV_PS_LCD_CHECK             "PS: LCD check: %d, %d"
#define   INFO_WNDRV_PS_CANT_TX_PROBE_REQ     "PS: Adapter not ready to send Probe Req frame %d"
#define   INFO_WNDRV_PS_SET_RSSIPROBECHK      "PS: Set bAdvRSSIProbeChk"

//20081201 add by lcko
#define   INFO_WNDRV_PS_SET_PS_MODE      "PS: Set to PS mode=%d"
#define   INFO_WNDRV_PM_STATE_TRANS    "PM TRANSITION: [%d] -> [%d]"
//20081208 add by lcko
#define   INFO_WNDRV_PS_SWITCH_BACK    "PS: Switch back to PS mode in deferred timer"
#define   INFO_WNDRV_PS_SWITCH_DISCONNECT    "PS: Cannot switch PS mode when disconnected"
#define   INFO_WNDRV_PS_SWITCH_CONT_POLL    "PS: Cannot switch PS mode during continuous polling"
#define   INFO_WNDRV_PS_SWITCH_TO_PS    "PS: Switch to PS mode"
//20081216 add by lcko
#define   INFO_WNDRV_PS_NULL    "PS: Send null packet with %d"
#define   INFO_WNDRV_PS_NULL_DIAG    "PS: pmSendNullFrameForConnectionDiagnostic"
//20090107 add by lcko
#define   INFO_WNDRV_PS_SWITCH_THE_SAME    "PS: The same PS mode: %d is set"
#define   INFO_WNDRV_PS_FPSP_TIME_ACCUM    "u4AccumRxUcPktNum: %d, u4RxUcPktNumThr: %d"
#define   INFO_WNDRV_PS_SWITCH_BACK_PSP    "PS: Switch back to PS mode in rPmSwitchPsModeTimer timer"
#define   INFO_WNDRV_PS_SWITCH_ACTIVE_PSP    "PS: Enter active mode for fast PSP"
#define   INFO_WNDRV_PS_SET_FPSP_TIMER    "PS: Set rPmSwitchPsModeTimer"
#define   INFO_WNDRV_PS_CANCEL_FPSP_TIMER    "PS: Cancel rPmSwitchPsModeTimer"
//20090205 add by lcko
#define   INFO_WNDRV_PS_ENTER_PS    "PS: Entering PS mode"
#define   INFO_WNDRV_PS_ALREADY_PS    "PS: Already in PS mode"
#define   INFO_WNDRV_PS_BLOCK_BY_SCAN    "PS: Blocked by scan %d"

/* --------------TRACE_GROUP_7 trace class (Roaming)------------------------------- */
#define   INFO_WNDRV_ROAMING_CHECK_LOST_LINK1          "ROAMING: Use NULL to test AP %02x:%02x:%02x:%02x:%02x:%02x..."
#define   INFO_WNDRV_ROAMING_CHECK_LOST_LINK2          "ROAMING: Lost beacon with AP %02x:%02x:%02x:%02x:%02x:%02x..."
#define   INFO_WNDRV_ROAMING_CHECK_LINK_QUALITY        "ROAMING: RSSI:%d High Threshold:%d Low Threshold:%d"
#define   INFO_WNDRV_ROAMING_CHECK_BETTER_ROAMING      "ROAMING: Check better AP then roaming"
#define   INFO_WNDRV_ROAMING_CHECK_RETRY_FAIL          "ROAMING: MPDU Retry Fail 0x%08x MPDU Retry:%d A1:%02x:%02x:%02x:%02x:%02x:%02x SQ:0x%04x"
#define   INFO_WNDRV_ROAMING_TEST_REMOTE_AP            "ROAMING: Test NULL Packet TFCB Status 0x%08x Retry: %d A1:%02x:%02x:%02x:%02x:%02x:%02x SQ:0x%04x"
#define   INFO_WNDRV_ROAMING_CHECK_RETRY_COUNT         "ROAMING: Check retry count: %d times"
#define   INFO_WNDRV_ROAMING_BACKGROUND_SCAN_INTERVAL    "ROAMING: Background Scan interval...currRssi=%d interval=%dms"
#define   INFO_WNDRV_ROAMING_BACKGROUND_SCAN_TX_NUM    "ROAMING: Background Scan TxDone=%d"
#define   INFO_WNDRV_ROAMING_BACKGROUND_SCAN_TIMEOUT    "ROAMING: Background Scan Timeout...next interval=%dms"
#define   INFO_WNDRV_ROAMING_BACKGROUND_SCAN_END       "ROAMING: Background Scan End..."
#define   INFO_WNDRV_ROAMING_CONFIDENCE_WINDOW_START    "ROAMING: Confidence Window Start...currRssi=%d otherRssi=%d"
#define   INFO_WNDRV_ROAMING_CONFIDENCE_WINDOW_COUNT    "ROAMING: Confidence Window Count: %d"
#define   INFO_WNDRV_ROAMING_CONFIDENCE_WINDOW_END     "ROAMING: Confidence Window End..."
#define   INFO_WNDRV_ROAMING_SCAN_AGAIN                "ROAMING: Scan again..."
#define   INFO_WNDRV_ROAMING_JOIN_AGAIN                "ROAMING: Join again..."

//20081127 add by saker
#define   INFO_WNDRV_ROAMING_SCAN_SET                  "ROAMING: SCAN TYPE:%d SCAN MIN TIME: %d ms, SCAN MAX TIME: %d ms, SCAN INTERVAL: %d ms, PS Mode: %d"
#define   INFO_WNDRV_ROAMING_SCAN_DONE                 "ROAMING: roaming Discovery Scan Done statue:%d"
#define   INFO_WNDRV_ROAMING_SCHED_PARTIAL_SCAN        "ROAMING: Schedule Next Partial Scan: Left Channel Number = %d, Total = %d"
#define   INFO_WNDRV_ROAMING_JOIN_FOR_ROAMING          "ROAMING: JOIN for roaming, AUTH TYPE = %d"
#define   INFO_WNDRV_ROAMING_SCAN_CANDIDATE            "ROAMING: Candidate [%02x-%02x-%02x-%02x-%02x-%02x]: RSSI = %d"
#define   INFO_WNDRV_ROAMING_SCAN_PRIMARY              "ROAMING: Primary [%02x-%02x-%02x-%02x-%02x-%02x]: RSSI = %d"
//20090226 add by lcko
#define   INFO_WNDRV_PS_SCAN_TO_IDLE                   "ROAMING: Change from SCAN to IDLE after disconnet"
//20090603 add by saker
#define   INFO_WNDRV_ROAMING_SUSPEND_PARTIAL_SCAN      "ROAMING: Suspend Partial Scan..."
#define   INFO_WNDRV_ROAMING_RESUME_PARTIAL_SCAN       "ROAMING: Resume Partial Scan..."
#define   INFO_WNDRV_ROAMING_NEXT_PARTIAL_SCAN         "ROAMING: Start Next Partial Scan..."
#define   INFO_WNDRV_ROMAING_TRIGGER_ANOTHER_SCAN      "ROAMING: Trigger Another Scan: %d..."


/* --------------TRACE_GROUP_8 trace class (Qos)----------------------------------- */

/* --------------TRACE_GROUP_9 trace class (Secuity)------------------------------- */
#define   INFO_WNDRV_CHECK_SECURITY_STATUS      "rxStatus: 0x%08x, secStatus: 0x%08x, dataByte: %d, frameCtrl: 0x%x, packet: 0x%04x"
#define   INFO_WNDRV_REOPEN_TRAFFIC             "Re-Open Traffic, rsnaBlockingTraffic = %d"
#define   INFO_WNDRV_COUNTERMEASURE_DISCONNECT    "rsnaTkipCtrMeausreDisconnect connDisconnectWithNetwork Seq:%d"
#define   INFO_WNDRV_TKIPHANDLEMICFAILURE         "tkipHandleMICFailure: %d, %d"
#define   INFO_WNDRV_TKIPHANDLEMICFAILURE_2       "Twice MIC fail: %d, %d, %d, %d"

/* --------------TRACE_GROUP_10 trace class (MISC)--------------------------------- */
#define   INFO_WNDRV_MISC_META_MODE      "WNDRV_MISC: meta_mode=%d"
#define   INFO_WNDRV_MISC_MACADDR        "WNDRV_MISC: cal_macaddr=0x%x %x %x %x %x %x"
#define   INFO_WNDRV_MISC_TXPWR_2400M    "WNDRV_MISC: cal_2.4g_pwr"
#define   INFO_WNDRV_MISC_TXPWR_5000M    "WNDRV_MISC: cal_5.0g_pwr"
#define   INFO_WNDRV_MISC_CHIP_CAP       "WNDRV_MISC: bb_chip=%d, rf_chip=%d, eeprom_exist=%d"
#define   INFO_WNDRV_MISC_TX_ALC_POWER    "WNDRV_MISC: cal_tx_alc_power"
//20091102 add by saker
#define   INFO_WNDRV_OID_ANT_TO_WIFI    "wlanoidSetPreferredAnt : Ant to WiFi"
#define   INFO_WNDRV_OID_ANT_TO_BT    "wlanoidSetPreferredAnt : Ant to BT"

#if defined(MT5931)
#define  LOUD_AAA_EVENT_TX_DONE    "EVENT-TX DONE:Current Time=%d\n"
#define  WARN_AAA_AuthAssocState_IDLE    "Previous AuthAssocState (%d) != IDLE.\n"
#define  WARN_AAA_AuthAssocState_SEND_AUTH2    "Previous AuthAssocState (%d) != SEND_AUTH2.\n"
#define  WARN_AAA_No_PKT_INFO_T    "No PKT_INFO_T for sending (Re)Assoc Response.\n"

#define  ERROR_SAA_EVENT_START_STATYPE_NOTSUPPORT    "EVENT-START: STA Type - %d was not supported.\n"
#define  ERROR_SAA_EVENT_START_REENTRY    "EVENT-START: Reentry of SAA Module.\n"
#define  ERROR_SAA_EVENT_UNKNOWN_AA_STATE    "Unknown AA STATE\n"
#define  WARN_SAA_No_PKT_INFO_T_REASSOC    "No PKT_INFO_T for sending (Re)Assoc Request.\n"
#define  WARN_SAA_No_PKT_INFO_T_DISASSOC    "No PKT_INFO_T for sending DisAssoc.\n"
#define  WARN_SAA_No_PKT_INFO_T_AUTH    "No PKT_INFO_T for sending Auth Frame.\n"
#define  WARN_SAA_STRANGE_AUTH_PACKET    "Strange Authentication Packet: Auth Trans Seq No = %d, Error Status Code = %d\n"
#define  WARN_SAA_No_UNUSED_DEAUTH_INFO_T    "No unused DEAUTH_INFO_T !\n"
#define  WARN_SAA_No_PKT_INFO_T_DEAUTH    "No PKT_INFO_T for sending Deauth Request.\n"
#define  STATE_SAA_TRANSITION    "TRANSITION: [%s] -> [%s]\n"
#define  TRACE_SAA_DEFAULT_INTERVAL    "Use default listen interval\n"
#define  INFO_SAA_AUTH_REJ    "Auth Req was rejected by [%02x:%02x:%02x:%02x:%02x:%02x], Status Code = %d\n"
#define  INFO_SAA_RX_DEAUTH    "Rx Deauth frame from BSSID=[%02x:%02x:%02x:%02x:%02x:%02x].\n"
#define  INFO_SAA_RX_DISASSOC    "Rx Disassoc frame from BSSID=[%02x:%02x:%02x:%02x:%02x:%02x].\n"
#define  LOUD_SAA_EVENT_START    "EVENT-START: Trigger SAA FSM\n"
#define  LOUD_SAA_ASSOC_REQ    "ASSOC REQ: Compose Capability = 0x%04x for Target BSS [%02x:%02x:%02x:%02x:%02x:%02x].\n"
#define  LOUD_SAA_prSwRfb    "prSwRfb->u2PayloadLength = %d\n"
#define  LOUD_SAA_Ignore_Disassoc_Frame    "Ignore Disassoc Frame from other BSS [%02x:%02x:%02x:%02x:%02x:%02x]\n"
#define  LOUD_SAA_Send_Auth_Frame    "Send Auth Frame\n"
#define  LOUD_SAA_Send_Auth_Frame_STATUS    "Send Auth Frame %d, Status Code = %d\n"
#define  LOUD_SAA_Discard_Auth_frame_TYPE    "Discard Auth frame with auth type = %d, current = %d\n"
#define  LOUD_SAA_Discard_Auth_frame_SEQ_NO    "Discard Auth frame with Transaction Seq No = %d\n"
#define  LOUD_SAA_Ignore_Deauth_Frame    "Ignore Deauth Frame from other BSS [%02x:%02x:%02x:%02x:%02x:%02x]\n"
#define  LOUD_SAA_EVENT_TX_DONE    "EVENT-TX DONE: Current Time = %d\n"
#define  LOUD_SAA_EVENT_TIMER_TX    "EVENT-TIMER: TX REQ TIMEOUT, Current Time = %d\n"
#define  LOUD_SAA_EVENT_TIMER_RX    "EVENT-TIMER: RX RESP TIMEOUT, Current Time = %d\n"
#define  LOUD_SAA_EVENT_ABORT    "EVENT-ABORT: Stop SAA FSM.\n"
#define  LOUD_SAA_EVENT_ABORT_STATE    "EVENT-ABORT: Previous Auth/Assoc State == %s.\n"

#define  ERROR_AIS_JOIN_INIT    "JOIN INIT: Auth Algorithm : %d was not supported by JOIN\n"
#define  ERROR_AIS_RETRY_JOIN_INIT    "RETRY JOIN INIT: Retry Authentication with Unexpected AuthType.\n"
#define  WARN_AIS_SEQ_SCN_NO_NOT_MATCH    "SEQ NO of AIS SCN DONE MSG is not matched.\n"
#define  WARN_AIS_SEQ_COMP_NO_NOT_MATCH    "SEQ NO of AIS JOIN COMP MSG is not matched.\n"
#define  WARN_AIS_SCAN_REQ_GRANTED    "Scan Request with channel granted for join operation: %d, %d"
#define  WARN_AIS_DEAUTH_FRAME    "DEAUTH frame transmitted without further handling"
#define  STATE_AIS_TRANSITION    "TRANSITION: [%s] -> [%s]\n"
#define  INFO_AIS_RETRY_JOIN_INIT    "RETRY JOIN INIT: Retry Authentication with AuthType == SHARED_KEY.\n"
#define  INFO_AIS_Postpone_INDICATION    "Postpone the indication of Disconnect for %d seconds\n"
#define  INFO_AIS_UPDATE_AIS_BSS_INFO_T    "Update AIS_BSS_INFO_T and apply settings to MAC\n"
#define  LOUD_AIS_JOIN_INIT_EAUTHMODE    "JOIN INIT: eAuthMode == AUTH_MODE_AUTO_SWITCH\n"
#define  LOUD_AIS_JOIN_INIT_AUTHTYPE    "JOIN INIT: AUTH TYPE = %d for Roaming\n"
#define  LOUD_AIS_JOIN_INIT_OPEN    "JOIN INIT: Try to do Authentication with AuthType == OPEN_SYSTEM.\n"
#define  LOUD_AIS_JOIN_INIT_SHARED_KEY    "JOIN INIT: Try to do Authentication with AuthType == SHARED_KEY.\n"
#define  LOUD_AIS_JOIN_INIT_FAST_BSS    "JOIN INIT: Try to do Authentication with AuthType == FAST_BSS_TRANSITION.\n"
#define  LOUD_AIS_SCAN    "SCAN: Idle Begin - Current Time = %d\n"
#define  LOUD_AIS_EVENT_SCAN_DONE    "EVENT-SCAN DONE: Current Time = %d\n"
#define  LOUD_AIS_EVENT_ABORT    "EVENT-ABORT: Current State %s\n"
#define  LOUD_AIS_EVENT_SCAN_TIMER    "EVENT - SCAN TIMER: Idle End - Current Time = %d\n"
#define  LOUD_AIS_EVENT_IBSS_ALONE_TIMER    "EVENT-IBSS ALONE TIMER: Start pairing\n"
#define  LOUD_AIS_EVENT_JOIN_TIMEOUT    "EVENT- JOIN TIMEOUT\n"
#define  LOUD_AIS_aisFsmRunEventRoamingDiscovery    "aisFsmRunEventRoamingDiscovery()\n"
#define  LOUD_AIS_aisFsmRoamingScanResultsUpdate    "->aisFsmRoamingScanResultsUpdate()\n"
#define  LOUD_AIS_aisFsmRoamingDisconnectPrevAP    "aisFsmRoamingDisconnectPrevAP()"
#define  LOUD_AIS_aisUpdateBssInfoForRoamingAP    "aisUpdateBssInfoForRoamingAP()"

#define  WARN_RLM_OBSS_Scan_Done    "OBSS Scan Done (NetIdx=%d) -- Aborted!!\n"
#define  WARN_RLM_OBSS_Scan_Timeout    "OBSS Scan timeout (NetIdx=%d) -- Aborted!!\n"
#define  INFO_RLM_NetIdx    "NetIdx=%d, ch=%d, SCO=%d, Erp=%d, Ht=%d, HtInfo1=%d\n"
#define  INFO_RLM_OBSS_Scan_Done    "OBSS Scan Done (NetIdx=%d)\n"
#define  INFO_RLM_Send_20_40_coexistence    "Send 20/40 coexistence mgmt(20mReq=%d, NonHt=%d)\n"
#define  INFO_RLM_Set_OBSS_timer    "Set OBSS timer (NetIdx=%d, %d sec)\n"
#define  INFO_RLM_Timeout    "Timeout to trigger OBSS scan (NetIdx=%d)!!\n"

#define  WARN_MEM_num_MgtDesc    "MgtDesc#=%d\n"
#define  WARN_MEM_rMgtBufInfo    "rMgtBufInfo: alloc#=%d, free#=%d, null#=%d\n"

#define  WARN_CNM_Init_timer    "Init timer with NULL callback function!\n"
#define  INFO_CNM_rTimeout    "rTimeout= %d\n"
#define  INFO_CNM_rTimeoutSystime    "rTimeoutSystime= %d, rExpiredSysTime= %d\n"
#define  INFO_CNM_rCurSysTime    "rCurSysTime= %d, prTimer->rExpiredSysTime= %d\n"
#define  LOUD_CNM_DO_MSG    "DO MSG [%d: %s]\n"

#define  WARN_BSS_DO_MSG    "No PKT_INFO_T for sending Null Frame.\n"
#define  WARN_BSS_prTxProbRspIETableWIP2P_NULL    "prTxProbRspIETableWIP2P is NULL\n"
#define  WARN_BSS_No_PKT_INFO_T    "No PKT_INFO_T for sending %s.\n"
#define  WARN_BSS_CLIENT_ALREADY_CONTAINED    "Current Client List already contains that STA_RECORD_T[%02x:%02x:%02x:%02x:%02x:%02x]\n"
#define  INFO_BSS_Ignore_HT    "Ignore the HT Bit for TKIP as pairwise cipher configed!\n"
#define  INFO_BSS_CLIENT_LIST    "Current Client List didn't contain that STA_RECORD_T[%02x:%02x:%02x:%02x:%02x:%02x] before removing.\n"
#define  INFO_BSS_PS_NOT_SUPPORTED    "AdHoc PS was not supported(ATIM Window: %d)\n"
#define  INFO_BSS_BCAST    "Bcast: eAci = %d, ACM = %d, Aifsn = %d, CWmin = %d, CWmax = %d, TxopLimit = %d\n"
#define  INFO_BSS_EACI    "eAci = %d, ACM = %d, Aifsn = %d, CWmin = %d, CWmax = %d, TxopLimit = %d\n"
#define  LOUD_BSS_Unsupported_Phy    "IBSS MERGE: Ignore Peer MAC: %02x:%02x:%02x:%02x:%02x:%02x - Unsupported Phy.\n"
#define  LOUD_BSS_Unknown_Basic_Rate    "IBSS MERGE: Ignore Peer MAC: %02x:%02x:%02x:%02x:%02x:%02x - Unknown Basic Rate.\n"
#define  LOUD_BSS_Capability_not_matched    "IBSS MERGE: Ignore Peer MAC: %02x:%02x:%02x:%02x:%02x:%02x - Capability is not matched.\n"
#define  LOUD_BSS_capability_passed    "IBSS MERGE: Peer MAC: %02x:%02x:%02x:%02x:%02x:%02x - Check capability was passed.\n"

#define  STATE_SCN_TRANSITION    "TRANSITION: [%s] -> [%s]\n"
#define  TRACE_SCN_Candidate    "Candidate [%02x:%02x:%02x:%02x:%02x:%02x]: RCPI = %d, Primary [%02x:%02x:%02x:%02x:%02x:%02x]: RCPI = %d\n"
#define  INFO_SCN_scnInit    "->scnInit()\n"
#define  INFO_SCN_scnUninit    "->scnUninit()\n"
#define  INFO_SCN_NUM_BSS_DESC_T    "SEARCH: Num Of BSS_DESC_T = %d, Look for SSID: %s\n"
#define  INFO_SCN_SEARCH_SSID    "SEARCH: [%02x:%02x:%02x:%02x:%02x:%02x], SSID:%s\n"
#define  INFO_SCN_Ignore_unsupported_ucPhyTypeSet    "SEARCH: Ignore unsupported ucPhyTypeSet = %x\n"
#define  INFO_SCN_Ignore_BSS    "SEARCH: Ignore BSS with previous Reason Code = %d\n"
#define  INFO_SCN_join_BSS    "SEARCH: Try to join BSS again which has Status Code = %d (Curr = %d/Last Join = %d)\n"
#define  INFO_SCN_maximum_retry_count    "SEARCH: Ignore BSS which reach maximum Join Retry Count = %d \n"
#define  INFO_SCN_Ignore_eBSSType    "SEARCH: Ignore eBSSType = %s\n"
#define  INFO_SCN_BSSID_not_matched    "SEARCH: Ignore due to BSSID was not matched!\n"
#define  INFO_SCN_Capability_not_supported    "SEARCH: Ignore BSS DESC MAC: %02x:%02x:%02x:%02x:%02x:%02x, Capability is not supported for current AdHoc Mode.\n"
#define  INFO_SCN_Smaller_TSF    "SEARCH: Ignore BSS DESC MAC: [%02x:%02x:%02x:%02x:%02x:%02x], Smaller TSF\n"
#define  INFO_SCN_SSID    "SSID %s\n"
#define  LOUD_SCN_SKIP_OLD_RECORD    "SEARCH: Skip old record of BSS Descriptor - BSSID:[%02x:%02x:%02x:%02x:%02x:%02x]\n\n"
#define  LOUD_SCN_prBssDesc    "SEARCH: prBssDesc->fgIsLargerTSF = %d\n"
#define  LOUD_SCN_Unexpected_Network_Type    "Unexpected Network Type: %d\n"

#define  INFO_P2P_BCN    "\n\rBCN: RX\n"

#define  WARN_QM_MARK_NULL_BSS    "Mark NULL the Packet for inactive Bss %u\n"
#define  WARN_QM_MARK_NULL_RFB    "Mark NULL the Packet for less Free Sw Rfb\n"
#define  WARN_QM_REORDERING_NULL_STA_REC    "Reordering for a NULL STA_REC, ucStaRecIdx = %d\n"
#define  WARN_QM_REORDERING_INVALID_STA_REC    "Reordering for an invalid STA_REC \n"
#define  WARN_QM_REORDERING_QUEPARM    "Reordering for a NULL ReorderQueParm \n"
#define  WARN_QM_DROP_PACKETS    "Drop packets (Inactive %u).\n"
#define  EVENT_QM_SIZEOF_AC_QUE_PARMS_T    "sizeof(AC_QUE_PARMS_T): %d \n"
#define  EVENT_QM_SIZEOF_CMD_UPDATE_WMM_PARMS    "sizeof(CMD_UPDATE_WMM_PARMS): %d \n"
#define  EVENT_QM_SIZEOF_IFI_CMD_T    "sizeof(WIFI_CMD_T): %d \n"
#define  EVENT_QM_MQM_QOS    "MQM: Assoc_Req Parsing (QoS Enabled=%d)\n"
#define  EVENT_QM_MQM_EACI    "MQM: eAci = %d, ACM = %d, Aifsn = %d, CWmin = %d, CWmax = %d, TxopLimit = %d\n"
#define  EVENT_QM_MQM_SCAN_RESULT    "MQM: Scan Result Parsing (WMM=%d, UAPSD=%d)\n"
#define  EVENT_QM_MQM_INCORRECT_SP_LENGTH    "MQM: Incorrect SP length \n"
#define  EVENT_QM_qmHandleEventBssAbsencePresence    "qmHandleEventBssAbsencePresence (ucNetTypeIdx=%d, fgIsAbsent=%d, FreeQuota=%d)\n"
#define  EVENT_QM_qmHandleEventStaChangePsMode    "qmHandleEventStaChangePsMode (ucStaRecIdx=%d, fgIsInPs=%d)\n"
#define  EVENT_QM_qmHandleEventStaUpdateFreeQuota    "qmHandleEventStaUpdateFreeQuota (ucStaRecIdx=%d, ucUpdateMode=%d, ucFreeQuota=%d)\n"
#define  INFO_QM_qmEnqueueTxPackets    "Enter qmEnqueueTxPackets\n"
#define  INFO_QM_queue_length    "Current queue length = %u\n"
#define  INFO_QM_TX_DA    "TX with DA = BMCAST\n"
#define  INFO_QM_TID_ROUND_HEAD_STA    "(Fairness) TID = %u Round Head STA = %u\n"
#define  INFO_QM_TID_SHARING_STA    "(Fairness) TID = %u Sharing STA = %u Resource = %u\n"
#define  INFO_QM_TID_SCHEDULED_STA    "(Fairness) TID = %u Scheduled Head STA = %u Left Resource = %u\n"
#define  INFO_QM_qmDequeueTxPacketsFromPerTypeQueues    "Enter qmDequeueTxPacketsFromPerTypeQueues (TC = %d, Max = %d)\n"
#define  LOUD_QM_qmDequeueTxPacketsFromPerStaQueues    "Enter qmDequeueTxPacketsFromPerStaQueues (TC = %u)\n"
#define  LOUD_QM_TID    "(Fairness) TID = %u Init Head STA = %u Resource = %u\n"
#define  LOUD_QM_qmDequeueTxPackets    "Enter qmDequeueTxPackets\n"
#define  LOUD_QM_Dequeue_packetss    "Dequeue packets from Per-STA queue[%u]\n"
#define  LOUD_QM_DQA    "DQA)[%u](%u)\n"
#define  LOUD_QM_num_dequeued_packets    "Current total number of dequeued packets = %u\n"
#define  LOUD_QM_Queue_packets_Absent    "Queue packets (Absent %u).\n"
#define  LOUD_QM_Queue_packets_PS    "Queue packets (PS %u).\n"
#define  LOUD_QM_orig_ucFreeQuota    "qmUpdateFreeQuota orig ucFreeQuota=%d Mode %u New %u\n"
#define  LOUD_QM_new_ucFreeQuota    "qmUpdateFreeQuota new ucFreeQuota=%d)\n"
#define  LOUD_QM_new_QuotaForDelivery    "new QuotaForDelivery = %d  QuotaForNonDelivery = %d\n"

#define  WARN_SEC_Length_TOO_SHORT    "WAPI IE length too short (length=%d)\n"
#define  WARN_SEC_Unsupported    "Unsupported WAPI IE version: %d\n"
#define  WARN_SEC_auth_key_mgt_suite_count    "Fail to parse WAPI IE in auth & key mgt suite count (IE len: %d)\n"
#define  WARN_SEC_auth_key_mgt_suite_list    "Fail to parse WAPI IE in auth & key mgt suite list (IE len: %d)\n"
#define  WARN_SEC_pairwise_cipher_suite_count    "Fail to parse WAPI IE in pairwise cipher suite count (IE len: %d)\n"
#define  WARN_SEC_pairwise_cipher_suite_list    "Fail to parse WAPI IE in pairwise cipher suite list (IE len: %d)\n"
#define  WARN_SEC_group_cipher_suite    "Fail to parse WAPI IE in group cipher suite (IE len: %d)\n"
#define  WARN_SEC_WAPI_capabilities    "Fail to parse WAPI IE in WAPI capabilities (IE len: %d)\n"
#define  TRACE_SEC_ALLOW    "Workaround the WAPI AP allow the customer to use WZC to join\n"
#define  TRACE_SEC_Selected_pairwise_group_cipher    "Selected pairwise/group cipher: %02x-%02x-%02x-%02x/%02x-%02x-%02x-%02x\n"
#define  TRACE_SEC_Selected_AKM_suite    "Selected AKM suite: %02x-%02x-%02x-%02x\n"
#define  TRACE_SEC_auth_mgt_suite    "WAPI: Assoc Info auth mgt suite [%d]: %02x-%02x-%02x-%02x\n"
#define  TRACE_SEC_pairwise_cipher_suite    "WAPI: Assoc Info pairwise cipher suite [%d]: %02x-%02x-%02x-%02x\n"
#define  TRACE_SEC_group_cipher_suite    "WAPI: Assoc Info group cipher suite : %02x-%02x-%02x-%02x\n"
#define  TRACE_SEC_IE_sz    "Assoc Info IE sz %d\n"
#define  INFO_SEC_No_Protected_BSS    "-- No Protected BSS\n"
#define  INFO_SEC_WAPI_Information    "WAPI Information Element does not exist.\n"
#define  INFO_SEC_Failed_select    "Failed to select pairwise/group cipher (0x%08x/0x%08x)\n"
#define  INFO_SEC_Cannot_support_AKM    "Cannot support any AKM suites\n"
#define  INFO_SEC_Not_WAPI_IE    "Not WAPI IE ?! u4SetBufferLen = %d\n"
#define  LOUD_SEC_group_key_cipher_suite    "WAPI: version %d, group key cipher suite %02x-%02x-%02x-%02x\n"
#define  LOUD_SEC_pairwise_key_cipher_suite    "WAPI: pairwise key cipher suite [%d]: %02x-%02x-%02x-%02x\n"
#define  LOUD_SEC_pairwise_key_cipher_suite_default    "WAPI: pairwise key cipher suite: %02x-%02x-%02x-%02x (default)\n"
#define  LOUD_SEC_AKM_suite    "WAPI: AKM suite [%d]: %02x-%02x-%02x-%02x\n"
#define  LOUD_SEC_AKM_suite_default    "WAPI: AKM suite: %02x-%02x-%02x-%02x (default)\n"
#define  LOUD_SEC_cap    "WAPI: cap: 0x%04x\n"

#define  STATE_ROAMING_TRANSITION    "TRANSITION: [%s] -> [%s]\n"
#define  EVENT_ROAMING_START    "EVENT-ROAMING START: Current Time = %d\n"
#define  EVENT_ROAMING_DISCOVERY    "EVENT-ROAMING DISCOVERY: Current Time = %d\n"
#define  EVENT_ROAMING_ROAM    "EVENT-ROAMING ROAM: Current Time = %d\n"
#define  EVENT_ROAMING_FAIL    "EVENT-ROAMING FAIL: reason %x Current Time = %d\n"
#define  EVENT_ROAMING_ABORT    "EVENT-ROAMING ABORT: Current Time = %d\n"
#define  LOUD_ROAMING_roamingFsmInit    "->roamingFsmInit(): Current Time = %d\n"
#define  LOUD_ROAMING_roamingFsmUninit    "->roamingFsmUninit(): Current Time = %d\n"
#define  LOUD_ROAMING_roamingFsmSendCmd    "->roamingFsmSendCmd(): Current Time = %d\n"
#define  LOUD_ROAMING_roamingFsmScanResultsUpdate    "->roamingFsmScanResultsUpdate(): Current Time = %d\n"
#define  LOUD_ROAMING_Timeout    "roamingFsmSteps: DiscoveryUpdateTime Timeout"
#define  LOUD_ROAMING_Updated    "roamingFsmSteps: DiscoveryUpdateTime Updated"
#define  LOUD_ROAMING_Current_Time    "ROAMING Process Events: Current Time = %d\n"

#define  INFO_SW1_aisFsmInit    "->aisFsmInit()\n"
#define  INFO_SW1_aisFsmUninit    "->aisFsmUninit()\n"

#define  WARN_SW4_No_PKT_INFO_T    "No PKT_INFO_T for sending Null Frame.\n"
#define  INFO_SW4_index    "index %d\n"
#define  INFO_SW4_prBeacon    "prBeacon allocation fail\n"
#define  INFO_SW4_MQM    "MQM: eAci = %d, ACM = %d, Aifsn = %d, CWmin = %d, CWmax = %d, TxopLimit = %d\n"
#define  INFO_SW4_ucBmpDeliveryAC    "[2] ucBmpDeliveryAC:0x%x, ucBmpTriggerAC:0x%x, ucUapsdSp:0x%x"
#define  LOUD_SW4_Read    "Read %u Index %u\n"


#define  ERROR_INIT_NOT_ALLOCATE    "Could not allocate %d bytes for %s.\n"
#define  ERROR_INIT_NOT_ALLOCATE_COALESCING    "Could not allocate %d bytes for coalescing buffer.\n"
#define  ERROR_INIT_NOT_ALLOCATE_INTERRUPT    "Could not allocate %d bytes for interrupt response.\n"
#define  ERROR_INIT_wlanImageSectionDownload    "wlanImageSectionDownload failed!\n"
#define  ERROR_INIT_ADAPTER_memory    "Allocate ADAPTER memory ==> FAILED\n"
#define  ERROR_INIT_CMD_INFO_T    "Allocate CMD_INFO_T ==> FAILED.\n"
#define  ERROR_INIT_nicInitializeAdapter    "nicInitializeAdapter failed!\n"
#define  ERROR_INIT_nicAllocateAdapterMemory    "nicAllocateAdapterMemory Error!\n"
#define  ERROR_INIT_nicpmSetDriverOwn    "nicpmSetDriverOwn() failed!\n"
#define  ERROR_INIT_Firmware_SCATTER_DL_FAIL    "Firmware scatter download failed!\n"
#define  ERROR_INIT_Firmware_DL_FAIL    "Firmware download failed!\n"
#define  ERROR_INIT_NO_Firmware    "No Firmware found!\n"
#define  ERROR_INIT_Init_Ready_bit    "Waiting for Init Ready bit: Timeout\n"
#define  ERROR_INIT_PLL_Ready_bit    "Waiting for PLL Ready bit: Timeout\n"
#define  ERROR_INIT_Ready_bit    "Waiting for Ready bit: Timeout\n"
#define  ERROR_INIT_DL_OK_DL_FAIL_bit    "Waiting for DL_OK/DL_FAIL bit: Timeout\n"
#define  ERROR_INIT_FWDL_RDY    "Waiting for FWDL_RDY: Timeout (0x%08X)\n"
#define  ERROR_INIT_get_TX_resource    "Fail to get TX resource return within timeout\n"
#define  ERROR_INIT_CMD_NIC_POWER_CTRL    "Fail to transmit CMD_NIC_POWER_CTRL command\n"
#define  ERROR_INIT_image_download    "Fail to transmit image download command\n"
#define  ERROR_INIT_WIFI_start    "Fail to transmit WIFI start command\n"
#define  ERROR_INIT_load_FW    "Fail to load FW image from file!\n"
#define  ERROR_INIT_DL_FAIL    "DL_FAIL detected: 0x%08X\n"
#define  WARN_INIT_INVALID_ETHER    "Invalid Ether packet length: %d\n"
#define  TRACE_INIT_CHIP_ID    "Chip ID: 0x%x\n"
#define  TRACE_INIT_Revision_ID    "Revision ID: 0x%x\n"
#define  TRACE_INIT_eNetTypeIndex    "eNetTypeIndex:%d, ePwrMode:%d, fgEnCmdEvent:%d\n"
#define  TRACE_INIT_Download_Address    "Download Address: 0x%08X\n"
#define  TRACE_INIT_Firmware_Length    "Firmware Length:  0x%08X\n"
#define  TRACE_INIT_INIT_RDY    "INIT-RDY detected\n"
#define  TRACE_INIT_PLL_RDY    "PLL-RDY detected\n"
#define  TRACE_INIT_DL_OK    "DL_OK detected\n"
#define  TRACE_INIT_wlanAdapterStart    "wlanAdapterStart(): Waiting for Ready bit..\n"
#define  TRACE_INIT_Ready_bit    "Ready bit asserted\n"
#define  TRACE_INIT_aucFreeBufferCount    "aucFreeBufferCount[%d]: %d, aucMaxNumOfBuffer[%d]: %d\n"
#define  TRACE_INIT_Drop_PORT_CONTROL    "Drop Tx packet due Port Control!\n"
#define  TRACE_INIT_Drop_KEY_REMOVED    "Drop Tx packet due the key is removed!!!\n"
#define  TRACE_INIT_Acquiring_LP_OWN    "wlanAdapterStart(): Acquiring LP-OWN\n"
#define  TRACE_INIT_fgEnArpFilter    "[1] fgEnArpFilter:0x%x, u4UapsdAcBmp:0x%x, u4MaxSpLen:0x%x"
#define  TRACE_INIT_Destination    "Destination: 0x%08x / Length: 0x%08x\n"
#define  TRACE_INIT_FWDL_RDY    "FWDL_RDY detected\n"
#define  TRACE_INIT_MCR_Read    "MCR Read: Offset = %#08x, Data = %#08x\n"
#define  TRACE_INIT_Rate_Changed    "[Stress Test] Rate is Changed to index %d...\n"
#define  TRACE_INIT_Channel_switched    "[Stress Test] Channel is switched to %d ...\n"
#define  TRACE_INIT_MCR_Write    "MCR Write: Offset = %#08x, Data = %#08x\n"
#define  INFO_INIT_Allocating    "Allocating %d bytes for %s.\n"
#define  INFO_INIT_Virtual_Address    "Virtual Address = %08x for %s.\n"
#define  INFO_INIT_ArParam    "ArParam %u %u %u %u\n"
#define  INFO_INIT_ArVer    "ArVer %u AbwVer %u AgiVer %u\n"
#define  INFO_INIT_HtMask    "HtMask %x LegacyMask %x\n"
#define  INFO_INIT_CheckWin    "CheckWin %u RateDownPer %u PerH %u PerL %u\n"

#define  ERROR_HAL_HAL_MCR_RD    "HAL_MCR_RD access fail! 0x%x: 0x%x \n"
#define  ERROR_HAL_HAL_MCR_WR    "HAL_MCR_WR access fail! 0x%x: 0x%x \n"
#define  ERROR_HAL_HAL_PORT_RD    "HAL_PORT_RD access fail! 0x%x\n"
#define  ERROR_HAL_HAL_PORT_WR    "HAL_PORT_WR access fail! 0x%x\n"
#define  ERROR_HAL_AL_BYTE_WR    "AL_BYTE_WR access fail! 0x%x\n"
#define  ERROR_HAL_kalDevReadAfterWriteWithSdioCmd52    "kalDevReadAfterWriteWithSdioCmd52 access fail!\n"
#define  WARN_HAL_HAL_MCR_RD    "ignore HAL_MCR_RD access! 0x%x\n"
#define  WARN_HAL_HAL_MCR_WR    "ignore HAL_MCR_WR access! 0x%x: 0x%x \n"
#define  WARN_HAL_HAL_PORT_RD    "ignore HAL_PORT_RD access! 0x%x\n"
#define  WARN_HAL_HAL_PORT_WR    "ignore HAL_PORT_WR access! 0x%x\n"
#define  WARN_HAL_AL_BYTE_WR    "ignore HAL_BYTE_WR access! 0x%x\n"
#define  WARN_HAL_HAL_DRIVER_OWN_BY_SDIO_CMD52    "ignore HAL_DRIVER_OWN_BY_SDIO_CMD52 access!\n"
#define  INFO_HAL_SET_SMT    "set smt fixed rate: %d \n"

#define  WARN_INTR_Un_handled_HISR    "Un-handled HISR %#x, HISR = %#x (HIER:0x%x)\n"
#define  WARN_INTR_Empty_INTR_handler    "Empty INTR handler! ISAR bit#: %d, event:%d, func: 0x%x\n"
#define  TRACE_INTR_Read_WHISR    "Read WHISR=%x\n"

#define  ERROR_REQ_Error    "Error, invalid WEP key ID: %d\n"
#define  ERROR_REQ_Invalid_WEP    "Invalid WEP key index: 0x%08x\n"
#define  ERROR_REQ_Invalid_WEP_ID    "invalid WEP key ID %u\n"
#define  ERROR_REQ_Invalid_KEY_INDEX    "invalid key index: 0x%08x\n"
#define  ERROR_REQ_Unknown_Encryption    "Unknown Encryption Status Setting:%d\n"
#define  ERROR_REQ_QueryBufferLen    "Invalid data. QueryBufferLen: %d.\n"
#define  ERROR_REQ_SetBufferLen    "Invalid data. SetBufferLen: %d.\n"
#define  ERROR_REQ_NVRAM_Read_Failed    "NVRAM Read Failed: index=%#x.\r\n"
#define  ERROR_REQ_NVRAM_Write_Failed    "NVRAM Write Failed.\r\n"
#define  TRACE_REQ_ucCmdSeqNum    "ucCmdSeqNum =%d\n"
#define  WARN_REQ_nicProcessIST    "Fail in set nicProcessIST! (Adapter not ready). ACPI=D%d, Radio=%d\n"
#define  WARN_REQ_MCR_WASR    "MCR_WASR: 0x%x \n"
#define  WARN_REQ_u4IntrBits    "u4IntrBits: 0x%x \n"


#define  ERROR_RX_kalProcessRxPacket    "kalProcessRxPacket return value != WLAN_STATUS_SUCCESS\n"
#define  ERROR_RX_EVENT_ID_BSS_BEACON_TIMEOUT    "EVENT_ID_BSS_BEACON_TIMEOUT: (ucNetTypeIdx = %d)\n"
#define  ERROR_RX_ucPacket    "ucPacketType = %d\n"
#define  ERROR_RX_Lentgh_Error    "Read RX Packet Lentgh Error\n"
#define  ERROR_RX_No_RX    "No RX packet\n"
#define  ERROR_RX_u4PktLen     "Read u4PktLen = %d, prHifRxHdr->u2PacketLen: %d\n"
#define  ERROR_RX_Packet_Length    "Packet Length = %d\n"
#define  ERROR_RX_Agg_Packet_Error    "Read RX Agg Packet Error\n"
#define  ERROR_RX_Response_Packet_Error    "Read Response Packet Error\n"
#define  WARN_RX_Stop_forward    "Stop to forward BMC packet due to less free Sw Rfb %u\n"
#define  WARN_RX_NO_BUFFER    "Not enough Event Buffer: required length = 0x%x, available buffer length = %d\n"
#define  TRACE_RX_non_IPv4_IPv6    "RX: \"non-IPv4/IPv6\" Packet\n"
#define  TRACE_RX_bad_IP_Checksum    "RX: \"bad IP Checksum\" Packet\n"
#define  TRACE_RX_bad_TCP_Checksum    "RX: \"bad TCP Checksum\" Packet\n"
#define  TRACE_RX_bad_UDP_Checksum    "RX: \"bad UDP Checksum\" Packet\n"
#define  TRACE_RX_prSkb    "prSkb->head = %x, prSkb->cb = %x\n"
#define  TRACE_RX_802_11_FORMAT    "HIF_RX_HDR_FLAG_802_11_FORMAT\n"
#define  TRACE_RX_REORDERING    "HIF_RX_HDR_FLAG_DO_REORDERING\n"
#define  TRACE_RX_BAR_FRAME    "HIF_RX_HDR_FLAG_BAR_FRAME\n"
#define  TRACE_RX_u2SSN    "u2SSN = %d, ucTid = %d\n"
#define  TRACE_RX_AMP_WDS    "HIF_RX_HDR_FLAG_AMP_WDS\n"
#define  TRACE_RX_pucBuf    "pucBuf= 0x%x, prHifRxHdr= 0x%x\n"
#define  TRACE_RX_u4PktLen    "RX%d: u4PktLen = %d\n"
#define  TRACE_RX_ucPacketType    "ucPacketType = %d\n"
#define  TRACE_RX_Dump_RX_buffer    "Dump RX buffer, length = 0x%x\n"
#define  TRACE_RX_No_RFB    "No More RFB\n"
#define  TRACE_RX_halRxFillRFB_FAIL    "halRxFillRFB failed\n"
#define  TRACE_RX_u4HwAppendDW    "u4HwAppendDW = 0x%x\n"
#define  TRACE_RX_u2PacketLen    "u2PacketLen = 0x%x\n"
#define  TRACE_RX_READ_ERROR    "Read RX Packet Lentgh Error (%d)\n"
#define  TRACE_RX_nicRxEnhanceRxReadBuffer    "nicRxEnhanceRxReadBuffer failed\n"
#define  TRACE_RX_i    "i = %d, u4PktLen = %d\n"
#define  TRACE_Dump_Response_buffer    "Dump Response buffer, length = 0x%x\n"
#define  INFO_RX_aucAddr1    "nicRx: aucAddr1: %02x:%02x:%02x:%02x:%02x:%02x\n"
#define  INFO_RX_aucAddr2    "nicRx: aucAddr2: %02x:%02x:%02x:%02x:%02x:%02x\n"
#define  INFO_RX_Deauth_Error    "Send Deauth Error\n"

#define  INFO_RSN_NO_STA_REC    "No STA rec!!\n"
#define  EVENT_RSN_ID_MIC_ERR_INFO    "EVENT_ID_MIC_ERR_INFO\n"

#define  EVENT_TX_pending    "----- pending frame %d -----\n"
#define  EVENT_TX_Acquire    "Acquire: TC = %d aucFreeBufferCount = %d\n"
#define  EVENT_TX_Release    "Release: i = %d aucFreeBufferCount = %d\n"
#define  EVENT_TX_TC    "@@@@@ TC = %u ucCurrentQuota = %u @@@@@\n"
#define  EVENT_TX_pending_len    "\n+++++ pending frame %d len = %d +++++\n"
#define  TRACE_TX_Polling    "Polling MCR_WTSR delay %d times, %d msec\n"
#define  TRACE_TX_Dump    "Dump CMD buffer, length = 0x%x, coalescingBuf_size = 0x%x\n"
#define  INFO_TX_ucStaRecIndex    "***** ucStaRecIndex = %d *****\n"
#define  INFO_TX_Round_Head_STA    "TC = %u Round Head STA = %u, u4HeadStaRecForwardCount = %u\n"
#define  WARN_TX_Forwarding    "Forwarding packet but Sta is STA_REC_INDEX_NOT_FOUND\n"
#define  WARN_TX_full_Tx_queue    "Drop the Packet for full Tx queue (forwarding) Bss %u\n"
#define  WARN_TX_inactive_Bss    "Drop the Packet for inactive Bss %u\n"

#define  TRACE_EMU_MCR_WTSR0    "MCR_WTSR0: 0x%x, MCR_WTSR1: 0x%x\n"




#define  MT5931_INFO_1    "[TETHERING][Rx_Auth]AUTHtoHOSTAP:prSwRfb%xpktlen%d"
#define  MT5931_INFO_2    "[TETHERING][Rx_Auth]StatusCode%dbyaaaFsmRunEventRxAuth"
#define  MT5931_INFO_3    "[TETHERING]aaaFsmRunEventRxAssoc:checkRxAuthflow!!!"
#define  MT5931_INFO_4    "prStaRec->eStaType%d"
#define  MT5931_INFO_5    "prStaRec->ucStaState%dAuthAssocState%d"
#define  MT5931_INFO_6    "RxAssoc:u2StatusCode%d"
#define  MT5931_INFO_7    "[TETHERING][Rx_Assoc]ASSOC_REQtoHOSTAP:prSwRfb%xpktlen%d"
#define  MT5931_INFO_8    "[TETHERING]AAA_STATE_SEND_AUTH2TXDone"
#define  MT5931_INFO_9    "aaaFsmRunEventTxDone(AUTH2):prMsduInfo%x"
#define  MT5931_INFO_10    "[TETHERING]AAA_STATE_SEND_AUTH2TXFail"
#define  MT5931_INFO_11    "[TETHERING]AAA_STATE_SEND_ASSOC2TXDone"
#define  MT5931_INFO_12    "aaaFsmRunEventTxDone(ASSOC2):prMsduInfo%x"
#define  MT5931_INFO_13    "[TETHERING]AAA_STATE_SEND_ASSOC2TXFail"
#define  MT5931_INFO_14    "AIS_STATE_TRANSITION:%d->%d"
#define  MT5931_INFO_15    "prBssDesc->aucBSSID:[%02x:%02x:%02x:%02x:%02x:%02x]prAisBssInfo->aucBSSID:[%02x:%02x:%02x:%02x:%02x:%02x]"
#define  MT5931_INFO_16    "authSendDeauthFramefail"
#define  MT5931_INFO_17    "SEQNO(%d)ofAISSCNDONEMSG(%d)isnotmatched"
#define  MT5931_INFO_18    "aisFsmRunEventScanDone:abnoramlAISSTATE%d"
#define  MT5931_INFO_19    "EVENT-ABORT:CurrentState%d"
#define  MT5931_INFO_20    "aisFsmRunEventFoundIBSSPeer:prAisIbssPeerFoundMsg->fgIsMergeIn=%d"
#define  MT5931_INFO_21    "aisUpdateBssInfoForCreateIBSS:prConnSettings->aucBSSID[%02x:%02x:%02x:%02x:%02x:%02x]"
#define  MT5931_INFO_22    "aisUpdateBssInfoForMergeIBSS:prConnSettings->aucBSSID[%02x:%02x:%02x:%02x:%02x:%02x]"
#define  MT5931_INFO_23    "prAisFsmInfo->eCurrentState[%d]prAisFsmInfo->fgIsInfraChannelFinished=%d"
#define  MT5931_INFO_24    "ScanRequestwithchannelgrantedforjoinoperation:%d,%d"
#define  MT5931_INFO_25    "aisFsmScanRequest:prAisFsmInfo->eCurrentState[%d]"
#define  MT5931_INFO_26    "prConnSettings->fgIsScanReqIssued%d"
#define  MT5931_INFO_27    "mismatchedgrant:prAisFsmInfo->ucSeqNumOfChReq%ducTokenID%d"
#define  MT5931_INFO_28    "BT_STATE_Report2WLAN=0x%x"
#define  MT5931_INFO_29    "rTxDoneStatus==TX_RESULT_DROPPED_IN_DRIVER"
#define  MT5931_INFO_30    "DEAUTHframetransmittedwithoutfurtherhandling"
#define  MT5931_INFO_31    "[TETHERING]IgnoreDisassocFramefromotherBSS[%02x:%02x:%02x:%02x:%02x:%02x]\n"
#define  MT5931_INFO_32    "NounusedDEAUTH_INFO_T!"
#define  MT5931_INFO_33    "NoPKT_INFO_TforsendingDeauthRequest."
#define  MT5931_INFO_34    "IgnoreDeauthFramefromotherBSS[%02x:%02x:%02x:%02x:%02x:%02x]"
#define  MT5931_INFO_35    "[TETHERING]NoPKT_INFO_Tforsending"
#define  MT5931_INFO_36    "[TETHERING]bssSendBeaconProbeResponse"
#define  MT5931_INFO_37    "[TETHERING]ProbeReqSTA:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_38    "CurrentClientListalreadycontainsthatSTA_RECORD_T[%02x:%02x:%02x:%02x:%02x:%02x]\n"
#define  MT5931_INFO_39    "CurrentClientListdidn'tcontainthatSTA_RECORD_T[%02x:%02x:%02x:%02x:%02x:%02x]beforeremoving.\n"
#define  MT5931_INFO_40    "ibssProcessMatchedBeacon:mboxSendMsg"
#define  MT5931_INFO_41    "fgIsChannelRequested%d"
#define  MT5931_INFO_42    "[CMD_ID_CH_PRIVILEGE]ucNetTypeIndex%ducTokenID%ducAction%ducPrimaryChannel%d"
#define  MT5931_INFO_43    "[CMD_ID_CH_PRIVILEGE]ucRfSco%ducRfBand%ducReqType%du4MaxInterval%d"
#define  MT5931_INFO_44    "[CMD_ID_CH_PRIVILEGE]BSSID:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_45    "[CMD_ID_CH_PRIVILEGE]ucNetTypeIndex%ducTokenID%ducAction%d"
#define  MT5931_INFO_46    "[EVENT_ID_CH_PRIVILEGE]ucNetTypeIndex%ducTokenID%ducPrimaryChannel%deRfSco%deRfBand%deReqType%du4GrantInterval%d"
#define  MT5931_INFO_47    "cnmStaFreeAllStaByNetType"
#define  MT5931_INFO_48    "cnmGetStaRecByIndex:[%d]fgIsInUse=NULL"
#define  MT5931_INFO_49    "ucNewState=%dprStaRec->ucStaState=%d"
#define  MT5931_INFO_50    "kalMsleep:%dms"
#define  MT5931_INFO_51    "kalIndicatePackets:apvPkts%x"
#define  MT5931_INFO_52    "kalIndicatePackets:freeFLC2buff%x"
#define  MT5931_INFO_53    "kalPacketFree:freeFLC2buff(DL)%x"
#define  MT5931_INFO_54    "kalPacketFree:freeFLC2buff(HS)%x"
#define  MT5931_INFO_55    "kalPacketFree:freeFLC2buff(MOD_TCPIP)%x"
#define  MT5931_INFO_56    "InvalidEtherpacketlength:%d\n"
#define  MT5931_INFO_57    "kalPacketAlloc:peer_p%xaddr%x:%x"
#define  MT5931_INFO_58    "freepoolid%dbuff_ptr%x"
#define  MT5931_INFO_59    "prAdapter->rMyMacAddr:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_60    "prAdapter->rWifiVar.aucInterfaceAddress:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_61    "prAdapter->rWifiVar.arBssInfo[NETWORK_TYPE_P2P_INDEX].aucOwnMacAddr:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_62    "!!!!!!!!!!LPcannotbeownback!!!!!!!!!"
#define  MT5931_INFO_63    "*(MT6255_CLKSQ_CON1)=%x"
#define  MT5931_INFO_64    "gpio_wifi_coclock_pinreg=%x"
#define  MT5931_INFO_65    "kalProcessRxPacketreturnvalue!=WLAN_STATUS_SUCCESS\n"
#define  MT5931_INFO_66    "prMsduInfo->aucEthDestAddr:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_67    "prTxCtrl->i4PendingFwdFrameCount%d"
#define  MT5931_INFO_68    "StoptoforwardBMCpacketduetolessfreeSwRfb%u\n"
#define  MT5931_INFO_69    "RX_PKT_DESTINATION_NULL"
#define  MT5931_INFO_70    "secCheckClassError()==FALSE"
#define  MT5931_INFO_71    "RXEVENTID:%x"
#define  MT5931_INFO_72    "[EVENT_ID_SCAN_DONE]ucSeqNum%d"
#define  MT5931_INFO_73    "RXEVENT:EVENT_ID_TX_DONEPacketSeq:%d,ucStatus:%d\n"
#define  MT5931_INFO_74    "bypassEVENT_ID_UPDATE_NOA_PARAMS"
#define  MT5931_INFO_75    "ucPacketType=%d\n"
#define  MT5931_INFO_76    "HIF_RX_PKT_TYPE_TX_LOOP:BACKucPacketType=%d\n"
#define  MT5931_INFO_77    "ucPacketType=%d\n"
#define  MT5931_INFO_78    "nicRxProcessRFBs:prSwRfb=NULL"
#define  MT5931_INFO_79    "nicRxReceiveRFBs:NoMoreRFB"
#define  MT5931_INFO_80    "nicRxReceiveRFBs:halRxFillRFBfailed"
#define  MT5931_INFO_81    "u4HwAppendDW=%x\n"
#define  MT5931_INFO_82    "u2PacketLen=%d\n"
#define  MT5931_INFO_83    "nicRxReturnRFB:prSwRfb%xprSwRfb->pvPacket%x"
#define  MT5931_INFO_84    "Acquire:TC=%daucFreeBufferCount=%d\n"
#define  MT5931_INFO_85    "Release:i=%daucFreeBufferCount=%d\n"
#define  MT5931_INFO_86    "FailtogetTXresourcereturnwithintimeout"
#define  MT5931_INFO_87    "FailtogetTXresourcereturnwithintimeout"
#define  MT5931_INFO_88    "TX_DMA:len%dbuf%x"
#define  MT5931_INFO_89    "TX1:Buf%xlen%d"
#define  MT5931_INFO_90    "TX2:Buf%xlen%d"
#define  MT5931_INFO_91    "TX3:Buf%xlen%d"
#define  MT5931_INFO_92    "nicTxMsduQueue(TX_PACKET_OS):MSDU%x"
#define  MT5931_INFO_93    "nicTxMsduQueue(TX_PACKET_FORWARDING):MSDU%x"
#define  MT5931_INFO_94    "prTxCtrl->i4PendingFwdFrameCount%d"
#define  MT5931_INFO_95    "nicProcessTxInterruptMCR_WTSR0:0x%x,MCR_WTSR1:0x%x\n"
#define  MT5931_INFO_96    "prTxCtrl->i4PendingFwdFrameCount%d"
#define  MT5931_INFO_97    "nicTxReturnMsduInfo:retrunprMsduInfo%x"
#define  MT5931_INFO_98    "nicTxFillMsduInfo:Net%dIs1x%dPktLen%dDestAddr:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_99    "QM:+STA[%d]\n"
#define  MT5931_INFO_100    "*****ucStaRecIndex=%d*****\n"
#define  MT5931_INFO_101    "ForwardingpacketbutStaisSTA_REC_INDEX_NOT_FOUND\n"
#define  MT5931_INFO_102    "DropthePacketforfullTxqueue(forwarding)Bss%u\n"
#define  MT5931_INFO_103    "DropthePacketforinactiveBss%u\n"
#define  MT5931_INFO_104    "rNotEnqueuedQueisnotempty%d"
#define  MT5931_INFO_105    "EnterqmDequeueTxPacketsFromPerStaQueues(TC=%u)\n"
#define  MT5931_INFO_106    "(Fairness)TID=%uInitHeadSTA=%uResource=%u\n"
#define  MT5931_INFO_107    "Deq0TC%dqueued%unet%umaclen%ulen%uType%u1x%u11%u\n"
#define  MT5931_INFO_108    "DestMac:%02x:%02x:%02x:%02x:%02x:%02x\n"
#define  MT5931_INFO_109    "DequeueTx:MSDU%x"
#define  MT5931_INFO_110    "QM:(BAR)(%d)(%d){%d,%d}\n"
#define  MT5931_INFO_111    "Droppackets(Inactive%u).\n"
#define  MT5931_INFO_112    "Queuepackets(Absent%u).\n"
#define  MT5931_INFO_113    "Queuepackets(PS%u).\n"
#define  MT5931_INFO_114    "Queuepackets(IsValid%u).\n"
#define  MT5931_INFO_115    "[EVENT_ID_BSS_ABSENCE_PRESENCE]ucNetTypeIdx%dfgIsAbsent%ducBssFreeQuota%d"
#define  MT5931_INFO_116    "qmHandleEventStaChangePsMode(ucStaRecIdx=%d,fgIsInPs=%d)\n"
#define  MT5931_INFO_117    "qmHandleEventStaChangePsMode:[%d]checkifdisconnected"
#define  MT5931_INFO_118    "qmHandleEventStaUpdateFreeQuota(ucStaRecIdx=%d,ucUpdateMode=%d,ucFreeQuota=%d)\n"
#define  MT5931_INFO_119    "rlmObssTriggerScan():cnmMemAlloc()fail"
#define  MT5931_INFO_120    "Add%02x:%02x:%02x:%02x:%02x:%02xwithpre-authtocandidatelist\n"
#define  MT5931_INFO_121    "Add%02x:%02x:%02x:%02x:%02x:%02xwithoutpre-authtocandidatelist\n"
#define  MT5931_INFO_122    "%02x:%02x:%02x:%02x:%02x:%02xatPMKIDcache!!\n"
#define  MT5931_INFO_123    "Add%02x:%02x:%02x:%02x:%02x:%02xtoPMKIDcache!!\n"
#define  MT5931_INFO_124    "BSSID:[%02x:%02x:%02x:%02x:%02x:%02x]"
#define  MT5931_INFO_125    "PrepareatimertoindicatecandidatePMKIDCandidate\n"
#define  MT5931_INFO_126    "prAisSpecificBssInfo->arPmkidCache[%d].rBssidInfo.arBSSID:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_127    "prAisSpecificBssInfo->arPmkidCandicate[%d].aucBssid:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_128    "%02x:%02x:%02x:%02x:%02x:%02x%d\n"
#define  MT5931_INFO_129    "%dprAisSpecificBssInfo->u4PmkidCacheCount=%dprAisSpecificBssInfo->u4PmkidCandicateCount=%d"
#define  MT5931_INFO_130    "rsnGeneratePmkidIndication#%d\n"
#define  MT5931_INFO_131    "[TETHERING]RxDeauthframefromBSSID=[%02x:%02x:%02x:%02x:%02x:%02x].\n"
#define  MT5931_INFO_132    "[TETHERING][Rx_Deauth]Rx_DeauthtoHOSTAP:prSwRfb%xpktlen%d"
#define  MT5931_INFO_133    "[TETHERING]RxDisassocframefromBSSID=[%02x:%02x:%02x:%02x:%02x:%02x].\n"
#define  MT5931_INFO_134    "[TETHERING][Rx_Disassoc]Rx_DisassoctoHOSTAP:prSwRfb%xpktlen%d"
#define  MT5931_INFO_135    "ELEM_ID_DS_PARAM_SET:ucIeDsChannelNum%d"
#define  MT5931_INFO_136    "CCMPPSK"
#define  MT5931_INFO_137    "ELEM_ID_HT_OP:ucIeHtChannelNum%d"
#define  MT5931_INFO_138    "WPAPSK"
#define  MT5931_INFO_139    "scanAddToBssDesc(DS):ucChannelNum%dprBssDesc->ucRCPI%dprHifRxHdr->ucRcpi%d"
#define  MT5931_INFO_140    "scanAddToBssDesc(HT):ucChannelNum%dprBssDesc->ucRCPI%dprHifRxHdr->ucRcpi%d"
#define  MT5931_INFO_141    "scanAddToBssDesc(NONE):ucChannelNum%dprBssDesc->ucRCPI%dprHifRxHdr->ucRcpi%d"
#define  MT5931_INFO_142    "prSwRfb->prHifRxHdr->ucRcpi%d"
#define  MT5931_INFO_143    "prSwRfb->prHifRxHdr->ucHwChannelNum%d"
#define  MT5931_INFO_144    "BSSID:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_145    "scanSearchBssDescByPolicy:ignoreBSSID[%02x:%02x:%02x:%02x:%02x:%02x]%ddBm<%ddBm"
#define  MT5931_INFO_146    "Candidate[%02x:%02x:%02x:%02x:%02x:%02x]:RCPI=%d,Primary[%02x:%02x:%02x:%02x:%02x:%02x]:RCPI=%d\n"
#define  MT5931_INFO_147    "SCANTRANSITION:%d->%d"
#define  MT5931_INFO_148    "[CMD_ID_SCAN_REQ]ucSeqNum%ducNetworkType%ducScanType%ducSSIDType%ducSSIDLength%d"
#define  MT5931_INFO_149    "[CMD_ID_SCAN_REQ]u2ChannelDwellTime%ducChannelType%ducChannelListNum%du2IELen%d"
#define  MT5931_INFO_150    "scnFsmMsgStart:scanpendinglist%d"
#define  MT5931_INFO_151    "[CMD_ID_SCAN_CANCEL]ucSeqNum%ducIsExtChannel%d"
#define  MT5931_INFO_152    "TC%u\n"
#define  MT5931_INFO_153    "Max%uFree%u\n"
#define  MT5931_INFO_154    "Average%uminReserved%uCurrentTcResource%uGuaranteedTcResource%u\n"
#define  MT5931_INFO_155    "TC%uHeadStaIdx%uForwardCount%u\n"
#define  MT5931_INFO_156    "BMCorunknownTxQueueLen%u\n"
#define  MT5931_INFO_157    "Pending%d\n"
#define  MT5931_INFO_158    "PendingSecurity%d\n"
#define  MT5931_INFO_159    "rFreeSwRfbList%u\n"
#define  MT5931_INFO_160    "rReceivedRfbList%u\n"
#define  MT5931_INFO_161    "rIndicatedRfbList%u\n"
#define  MT5931_INFO_162    "ucNumIndPacket%u\n"
#define  MT5931_INFO_163    "ucNumRetainedPacket%u\n"
#define  MT5931_INFO_164    "Macaddress:%02x:%02x:%02x:%02x:%02x:%02xRcpi%u\n"
#define  MT5931_INFO_165    "Idx%uWtbl%uUsed%uState%uBssPhy%xStaDesiredPhy%x\n"
#define  MT5931_INFO_166    "StaOperation%xDesiredNontHtRateSet%xMcs%xu2HtCapInfo%xu2CapInfo%x\n"
#define  MT5931_INFO_167    "TC%uQueueLen%u\n"
#define  MT5931_INFO_168    "BmpDeliveryAC%x\n"
#define  MT5931_INFO_169    "BmpTriggerAC%x\n"
#define  MT5931_INFO_170    "UapsdSpSupproted%u\n"
#define  MT5931_INFO_171    "IsQoS%u\n"
#define  MT5931_INFO_172    "AssocId%u\n"
#define  MT5931_INFO_173    "fgIsInPS%u\n"
#define  MT5931_INFO_174    "ucFreeQuota%u\n"
#define  MT5931_INFO_175    "ucFreeQuotaForDelivery%u\n"
#define  MT5931_INFO_176    "ucFreeQuotaForNonDelivery%u\n"
#define  MT5931_INFO_177    "OWN%02x:%02x:%02x:%02x:%02x:%02x\n"
#define  MT5931_INFO_178    "BSSID%02x:%02x:%02x:%02x:%02x:%02x\n"
#define  MT5931_INFO_179    "ucNetTypeIndex%u\n"
#define  MT5931_INFO_180    "eConnectionState%u\n"
#define  MT5931_INFO_181    "eCurrentOPMode%u\n"
#define  MT5931_INFO_182    "fgIsQBSS%u\n"
#define  MT5931_INFO_183    "fgIsShortPreambleAllowed%u\n"
#define  MT5931_INFO_184    "fgUseShortPreamble%u\n"
#define  MT5931_INFO_185    "fgUseShortSlotTime%u\n"
#define  MT5931_INFO_186    "ucNonHTBasicPhyType%x\n"
#define  MT5931_INFO_187    "u2OperationalRateSet%x\n"
#define  MT5931_INFO_188    "u2BSSBasicRateSet%x\n"
#define  MT5931_INFO_189    "ucPhyTypeSet%x\n"
#define  MT5931_INFO_190    "rStaRecOfClientList%d\n"
#define  MT5931_INFO_191    "u2CapInfo%x\n"
#define  MT5931_INFO_192    "u2ATIMWindow%x\n"
#define  MT5931_INFO_193    "u2AssocId%x\n"
#define  MT5931_INFO_194    "ucDTIMPeriod%x\n"
#define  MT5931_INFO_195    "ucDTIMCount%x\n"
#define  MT5931_INFO_196    "fgIsNetAbsent%x\n"
#define  MT5931_INFO_197    "eBand%d\n"
#define  MT5931_INFO_198    "ucPrimaryChannel%d\n"
#define  MT5931_INFO_199    "ucHtOpInfo1%d\n"
#define  MT5931_INFO_200    "ucHtOpInfo2%d\n"
#define  MT5931_INFO_201    "ucHtOpInfo3%d\n"
#define  MT5931_INFO_202    "fgErpProtectMode%d\n"
#define  MT5931_INFO_203    "eHtProtectMode%d\n"
#define  MT5931_INFO_204    "eGfOperationMode%d\n"
#define  MT5931_INFO_205    "eRifsOperationMode%d\n"
#define  MT5931_INFO_206    "fgObssErpProtectMode%d\n"
#define  MT5931_INFO_207    "eObssHtProtectMode%d\n"
#define  MT5931_INFO_208    "eObssGfProtectMode%d\n"
#define  MT5931_INFO_209    "fgObssRifsOperationMode%d\n"
#define  MT5931_INFO_210    "fgAssoc40mBwAllowed%d\n"
#define  MT5931_INFO_211    "fg40mBwAllowed%d\n"
#define  MT5931_INFO_212    "eBssSCO%d\n"
#define  MT5931_INFO_213    "=====MT5931E%d====="
#define  MT5931_INFO_214    "[COCLK]Mode:%dPIN:%d"
#define  MT5931_INFO_215    "WaitingforPLLReadybit:Timeout"
#define  MT5931_INFO_216    "*(MT6255_CLKSQ_CON1)=%x"
#define  MT5931_INFO_217    "gpio_wifi_coclock_pinreg=%x"
#define  MT5931_INFO_218    "[wlanAdapterStart]firsttimeinit"
#define  MT5931_INFO_219    "[wlanAdapterStop]alwayson"
#define  MT5931_INFO_220    "COMMAND_TYPE_SECURITY_FRAME:eFrameAction%d"
#define  MT5931_INFO_221    "rWifiVar.aucPermanentAddress:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_222    "rWifiVar.aucMacAddress:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_223    "u2FwProductID%xu2FwOwnVersion%x"
#define  MT5931_INFO_224    "ucCmdSeqNum=%d/CmdID=%x\n"
#define  MT5931_INFO_225    "wlanEnqueueTxPacket:MSDU%x"
#define  MT5931_INFO_226    "\n+++++pendingframe%dlen=%d+++++\n"
#define  MT5931_INFO_227    "ucCmdSeqNum=%d/CmdID=%x\n"
#define  MT5931_INFO_228    "badWPSATTRtype=%x"
#define  MT5931_INFO_229    "badWPSATTRlen=%x"
#define  MT5931_INFO_230    "copyattr=%x,len=%d"
#define  MT5931_INFO_231    "attristoolarge,discard"
#define  MT5931_INFO_232    "Addkey:PrepareatimertoindicatecandidatePMKIDCandidate\n"
#define  MT5931_INFO_233    "AddBSSID%02x:%02x:%02x:%02x:%02x:%02xidx=%dPMKIDvalue%02x:%02x:%02x:%02x:%02x:%02x\n"
#define  MT5931_INFO_234    "SetWi-FiPSmodetoCAM(%d)\n"
#define  MT5931_INFO_235    "SetWi-FiPSmodetoMAXPS(%d)\n"
#define  MT5931_INFO_236    "SetWi-FiPSmodetoFASTPS(%d)\n"
#define  MT5931_INFO_237    "invalidWi-FiPSmodesetting(%d)\n"
#define  MT5931_INFO_238    "prNetAddrIp->in_addr:%d:%d:%d:%d\n"
#define  MT5931_INFO_239    "ucCmdSeqNum=%d/CmdID=%x\n"
#define  MT5931_INFO_240    "[TETHERING]AAAcomplete[%02x:%02x:%02x:%02x:%02x:%02x]\n"
#define  MT5931_INFO_241    "DisconnectSTA:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_242    "DisconnectSTA:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_243    "[TETHERING][Rx_Auth]wtValidateAuth:cnmStaRecAllocucIndex%d"
#define  MT5931_INFO_244    "[TETHERING][Rx_Auth]wtValidateAuth:cnmStaRecChangeStateSTA_STATE_1"
#define  MT5931_INFO_245    "[TETHERING][Rx_Auth]wtValidateAuth:prStaRec->ucIndex=%x"
#define  MT5931_INFO_246    "[TETHERING][Rx_Auth]wtValidateAuth:STARECNum%dreachLIMIT(%d)"
#define  MT5931_INFO_247    "[TETHERING][Rx_Auth]wtValidateAuth:fgReplyAuth,%x"
#define  MT5931_INFO_248    "RX_ASSOC:prStaRec=NULL"
#define  MT5931_INFO_249    "[TETHERING][Rx_Assoc]wtValidateAssocReq:fgReplyAssocResp,%x"
#define  MT5931_INFO_250    "[TETHERING]ProbeRequestRateSetonlycontains11Brate"
#define  MT5931_INFO_251    "[TETHERING]prIeSsid=NULL"
#define  MT5931_INFO_252    "[TETHERING]P2PSSIDnotWildcardSSIDornotP2PWildcardSSID"
#define  MT5931_INFO_253    "wtRunEventChGrant:[u4GrantInterval%d]"
#define  MT5931_INFO_254    "wtRunEventChGrant:[ucSeqNumOfChReq:%d][ucTokenID:%d]"
#define  MT5931_INFO_255    "prBssInfo->aucOwnMacAddr:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_256    "prBssInfo->aucBSSID:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_257    "prAdapter->rWifiVar.aucDeviceAddress:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_258    "AddGTK"
#define  MT5931_INFO_259    "[TETHERING]DisconnectSTA:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_260    "B-onlymode"
#define  MT5931_INFO_261    "BG-only/A-onlymode"
#define  MT5931_INFO_262    "20MHZ-only"
#define  MT5931_INFO_263    "Longpreamble"
#define  MT5931_INFO_264    "ucCmdSeqNum=%d/CmdID=%x\n"
#define  MT5931_INFO_265    "DeauthTXDone"
#define  MT5931_INFO_266    "StationRecordNULL,Index:%d\n"
#define  MT5931_INFO_267    "[APNIC]essid_flag%d"
#define  MT5931_INFO_268    "[AID=%d]StaAddr:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_269    "!!!SHOULDwtRunEventAAACompleteFIRST!!!"
#define  MT5931_INFO_270    "[TETHERING]ADD_STA:%d"
#define  MT5931_INFO_271    "StaAddr:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_272    "!!!RemoveSTA:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_273    "[WARNING]CannotFindSTA%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_274    "[TETHERING]REMOVE_STA:%d"
#define  MT5931_INFO_275    "[ERROR]CANNOTFINDSTA:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_276    "[WPA2-PSK]CarryRSNIE"
#define  MT5931_INFO_277    "[Open]Carrynone"
#define  MT5931_INFO_278    "authSendAuthFrameDst:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_279    "assocSendReAssocRespFrameDst:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_280    "[ERROR!!]prStaRec=NULL,sendhostapframefail"
#define  MT5931_INFO_281    "[TETHERING]TXEAPOL:peer_buff%x"
#define  MT5931_INFO_282    "[THTHERING]sendDEAUTH/DISASSOCfromHOSTAP(TBD.)"
#define  MT5931_INFO_283    "[THTHERING]bypasssendDEAUTH/DISASSOCfromHOSTAP"
#define  MT5931_INFO_284    "resumeSPDU_HS"
#define  MT5931_INFO_285    "setdecpower=%d,powerctrlTO=%d*100ms"
#define  MT5931_INFO_286    "WHCR:%x\n"
#define  MT5931_INFO_287    "[eHPItest]DataCompareerror,TXMode:%x,RXMode\n"
#define  MT5931_INFO_288    "DclSDIO_Openfailed,handle_sdio=%x"
#define  MT5931_INFO_289    "SDIOClosedfailed!!"
#define  MT5931_INFO_290    "InitializeSDIOfailed,Status=%x"
#define  MT5931_INFO_291    "InitializeSDIOCTRLfailed,Status=%x"
#define  MT5931_INFO_292    "SDIO_CTRL_CMD_MCUDMA_WRITEfailed!!"
#define  MT5931_INFO_293    "SDIO_CTRL_CMD_MCUDMA_READfailed!!"
#define  MT5931_INFO_294    "SDIO_CTRL_CMD_GETCLKCMDFailed!!"
#define  MT5931_INFO_295    "SDIO_CTRL_CMD_GETCLK=%x"
#define  MT5931_INFO_296    "SDIO_CTRL_CMD_SETCLKCMDFailed!!"
#define  MT5931_INFO_297    "SDIO_CTRL_CMD_SET_BLK_SIZEfailed!!"
#define  MT5931_INFO_298    "FUNC1BLKSIZE:%x"
#define  MT5931_INFO_299    "wndrv_coclock_eint_registerdone!!"
#define  MT5931_INFO_300    "wndrv_coclock_eint_registerdone!!"
#define  MT5931_INFO_301    "[kalDevRegRead]%x:%x"
#define  MT5931_INFO_302    "[kalDevRegWrite]%x:%x"
#define  MT5931_INFO_303    "[kalDevRegReadWorkAround]%x:%x"
#define  MT5931_INFO_304    "[kalDevRegWriteWorkAround]%x:%x"
#define  MT5931_INFO_305    "kalDevPortWrite:u2Len%di%d"
#define  MT5931_INFO_306    "reaminoddvalue%d"
#define  MT5931_INFO_307    "REGSelectionNosupport"
#define  MT5931_INFO_308    "wndrv_lcd_power_control%dwrongsetting"
#define  MT5931_INFO_309    "wndrv_lcd_power_control%dwrongsetting"
#define  MT5931_INFO_310    "hostap_wndrv_msg_handler!!!SHOULDNOTENTER!!!"
#define  MT5931_INFO_311    "utSendProbeRequest!!!SHOULDNOTENTER!!!"
#define  MT5931_INFO_312    "wlanTxDataPacket!!!SHOULDNOTENTER!!!"
#define  MT5931_INFO_313    "wndrv_main:Unexpectedilm_ptr->msg_id:%d"
#define  MT5931_INFO_314    "PARAM_WNDRV_ES_TEST_TIMERtimeout"
#define  MT5931_INFO_315    "PARAM_WNDRV_ES_CNM_TIMERtimeout"
#define  MT5931_INFO_316    "PARAM_WNDRV_ES_PWR_CTRL_TIMR"
#define  MT5931_INFO_317    "WIFI_DEGRADE_POWER:degrade%ddB!"
#define  MT5931_INFO_318    "WIFI_DEGRADE_POWER:resume!"
#define  MT5931_INFO_319    "PARAM_WNDRV_ES_BEACON_TIMRtimeout"
#define  MT5931_INFO_320    "OpenSDIOfailed!!"
#define  MT5931_INFO_321    "OpenSDIOfailed!!"
#define  MT5931_INFO_322    "CustomSettingVer%d<%d.settodefault"
#define  MT5931_INFO_323    "wndrv_context.glue_p->as4Cust_config[%d]=%d"
#define  MT5931_INFO_324    "*(MT6256_CLKSQ_CON1)=%x"
#define  MT5931_INFO_325    "*(MT6255_CLKSQ_CON1)=%x"
#define  MT5931_INFO_326    "[L1]wndrv_one()"
#define  MT5931_INFO_327    "tcpip_wndrv_data_req_handler:peer_p->free_header_space=%d<%d"
#define  MT5931_INFO_328    "tcpip_wndrv_data_req_handler:peer_p%xheaderspace%d"
#define  MT5931_INFO_329    "prPacketInfo->pDestAddr:%02x:%02x:%02x:%02x:%02x:%02xpeer_p%x"
#define  MT5931_INFO_330    "storeawpsprobereqinadapter"
#define  MT5931_INFO_331    "WIFIModeSwitchtoWAPIMode"
#define  MT5931_INFO_332    "WAPIModeSwitchtoWIFIMode"
#define  MT5931_INFO_333    "ModeNoChange"
#define  MT5931_INFO_334    "wndrv_supc_join_network_req_hanlder:wlanoidSetInfrastructureModefailNoChange:%d"
#define  MT5931_INFO_335    "Settoauthmodestatus%d\n"
#define  MT5931_INFO_336    "Settoencryptmodestatus%d\n"
#define  MT5931_INFO_337    "SettoWAPIModestatus%d"
#define  MT5931_INFO_338    "Settoassocinfostatus%d"
#define  MT5931_INFO_339    "WAPIMODEADDKEY"
#define  MT5931_INFO_340    "SetWapiKey"
#define  MT5931_INFO_341    "SetwlanoidSetWapiKeyDone"
#define  MT5931_INFO_342    "[L1]wndrv_four()"
#define  MT5931_INFO_343    "iScanResultCount:%d"
#define  MT5931_INFO_344    "wndrv_supc_site_survey_ind_handler:SCANWAPIAP!WAPI_IE_LEN:%d,BSSID%x:%x:%x:%x:%x:%x"
#define  MT5931_INFO_345    "WPSAPBSSID%x:%x:%x:%x:%x:%x\nnettype=%d"
#define  MT5931_INFO_346    "[L1]wndrv_two()"
#define  MT5931_INFO_347    "[L1]wndrv_three():progress:%d"
#define  MT5931_INFO_348    "[ServiceAPI]SetPowerMode:%d"
#define  MT5931_INFO_349    "[BWCS]setPTAmode8:VAR_WMT_CONFIG_WIFI_1WIRE_MODE|VAR_1WIRE_MODE|BT_EXT_1_WIRE_EXTEND_MODE"
#define  MT5931_INFO_350    "[BWCS]setPTAtiming:VAR_WMT_CONFIG_WIFI_1WIRE_MODE|PARAM_CUST_SET_BT_1WIRE_MODE_T6|0x%x"
#define  MT5931_INFO_351    "[BWCS]setPTAtiming:VAR_WMT_CONFIG_WIFI_1WIRE_MODE|PARAM_CUST_SET_BT_1WIRE_MODE_T8|0x%x"
#define  MT5931_INFO_352    "[BWCS]setPTAtiming:VAR_WMT_CONFIG_WIFI_1WIRE_MODE|PARAM_CUST_SET_BT_1WIRE_MODE_BT_DELAY|0x%x"
#define  MT5931_INFO_353    "[BWCS]setUCM/SCM:VAR_WIFI_COEX_MODE_REQ|VAR_WIFI_COEX_MODE_UC"
#define  MT5931_INFO_354    "[BWCS]setUCM/SCM:VAR_WIFI_COEX_MODE_REQ|VAR_WIFI_COEX_MODE_SC"
#define  MT5931_INFO_355    "(1)[BWCS]ind_p->ucBt_tsco=%d"
#define  MT5931_INFO_356    "(2)[BWCS]ind_p->ucBt_tsco=%d"
#define  MT5931_INFO_357    "[BWCS]setBTprofile:VAR_WMT_REPORT_BT_PROFILE|VAR_BT_PROF_LINK_CONNECTED|VAR_BT_PROF_ESCO|VAR_BT_PROF_SCO"
#define  MT5931_INFO_358    "[BWCS]setBTprofile:VAR_WMT_REPORT_BT_PROFILE|VAR_BT_PROF_LINK_CONNECTED|VAR_BT_PROF_SCO"
#define  MT5931_INFO_359    "[BWCS]setBTprofile:VAR_WMT_REPORT_BT_PROFILE|VAR_BT_PROF_LINK_CONNECTED"
#define  MT5931_INFO_360    "[BWCS]setBTprofile:VAR_WMT_REPORT_BT_PROFILE|VAR_BT_PROF_LINK_CONNECTED|VAR_BT_PROF_A2DP"
#define  MT5931_INFO_361    "(2)[BWCS]ind_p->ucBt_tsco=%d"
#define  MT5931_INFO_362    "[BWCS]setBTprofile:VAR_WMT_REPORT_BT_PROFILE|VAR_BT_PROF_LINK_CONNECTED|VAR_BT_PROF_ESCO|VAR_BT_PROF_SCO"
#define  MT5931_INFO_363    "[BWCS]setBTprofile:VAR_WMT_REPORT_BT_PROFILE|VAR_BT_PROF_LINK_CONNECTED|VAR_BT_PROF_SCO"
#define  MT5931_INFO_364    "[BWCS]setBTprofile:VAR_WMT_REPORT_BT_PROFILE|VAR_BT_PROF_NONE"
#define  MT5931_INFO_365    "[BWCS]setCOEXsetting:VAR_WMT_CONFIG_COEX_SETTING"
#define  MT5931_INFO_366    "[BWCS]|WMT_COEX_CONFIG_ENABLE_PTA"
#define  MT5931_INFO_367    "[BWCS]|WMT_COEX_CONFIG_DUAL_ANT_MODE"
#define  MT5931_INFO_368    "[BWCS]|WMT_COEX_CONFIG_ENABLE_RW"
#define  MT5931_INFO_369    "[BWCS]VAR_WMT_CONFIG_COEX_SETTING&(~WMT_COEX_CONFIG_BT_ON)"
#define  MT5931_INFO_370    "[BWCS]|WMT_COEX_CONFIG_BT_ON|WMT_COEX_CONFIG_WIFI_ON"
#define  MT5931_INFO_371    "CONNSTATUSnochange,bypassupdatetoBWCS"
#define  MT5931_INFO_372    "timer_switch=%d,wifi_ms=%d,bt_ms=%d"

#define  MT5931_INFO_401    "prBssInfo->fgIsBeaconActivated=%d"
#define  MT5931_INFO_402    "prBssDesc->aucSrcAddr:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_403    "IBSSMERGE:IgnorePeerMAC:%02x:%02x:%02x:%02x:%02x:%02x-UnsupportedPhy."
#define  MT5931_INFO_404    "IBSSMERGE:IgnorePeerMAC:%02x:%02x:%02x:%02x:%02x:%02x-UnknownBasicRate."
#define  MT5931_INFO_405    "IBSSMERGE:IgnorePeerMAC:%02x:%02x:%02x:%02x:%02x:%02x-Capabilityisnotmatched."
#define  MT5931_INFO_406    "IBSSMERGE:IgnorePeerMAC:%02x:%02x:%02x:%02x:%02x:%02x-Capabilityisnotmatched."
#define  MT5931_INFO_407    "IBSSMERGE:PeerMAC:%02x:%02x:%02x:%02x:%02x:%02x-Checkcapabilitywaspassed."
#define  MT5931_INFO_408    "nicIncreaseTxSeqNum:ucTxSeqNum=%d"
#define  MT5931_INFO_409    "rCmdSetBssInfo.aucBSSID:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_410    "rCmdSetBssInfo.aucOwnMac:%02x:%02x:%02x:%02x:%02x:%02x"
#define  MT5931_INFO_411    "rCmdSetBssInfo.ucAuthMode:%drCmdSetBssInfo.ucEncStatus:%d"
#define  MT5931_INFO_412    "nicUpdateBss:PARAM_MEDIA_STATE_DISCONNECTED"
#define  MT5931_INFO_413    "badWPSfragment"
#define  MT5931_INFO_414    "add%dbytesattr"
#define  MT5931_INFO_415    "discardwpsattributes,wps_ieisfull"
#define  MT5931_INFO_416    "resumeIEbuffer%d"
#define  MT5931_INFO_417    "resumeIEbuffer%d"
#define  MT5931_INFO_418    "badWPSfragment"
#define  MT5931_INFO_419    "add%dbytesattr"
#define  MT5931_INFO_420    "discardwpsattributes,wps_ieisfull"
#define  MT5931_INFO_421    "resumeIEbuffer%d"
#define  MT5931_INFO_422    "resumeIEbuffer%d"
#define  MT5931_INFO_423    "badWPSfragment"
#define  MT5931_INFO_424    "add%dbytesattr"
#define  MT5931_INFO_425    "discardwpsattributes,wps_ieisfull"
#define  MT5931_INFO_426    "resumeIEbuffer%d"
#define  MT5931_INFO_427    "resumeIEbuffer%d"
#define  MT5931_INFO_428    "[MT5931][wifi][Firmware]Assertat\"%c%c%c%c%c%c\"#%d"
#define  MT5931_INFO_429    "InvalidBeaconFrame(u2PacketLen=%d,u2HeaderLen=%d)"
#define  MT5931_INFO_430    "[eHPItest]1.ChipID/RevisionID"
#define  MT5931_INFO_431    "[eHPItest]ChipID/RevisionID=%x"
#define  MT5931_INFO_432    "noresource"
#define  MT5931_INFO_433    "wlanSendCommand:WLAN_STATUS_RESOURCES:NOResource:%d\n"
#define  MT5931_INFO_434    "Destination:0x%08x/Length:0x%08x"
#define  MT5931_INFO_435    "FWDL_RDYdetected"
#define  MT5931_INFO_436    "WaitingforFWDL_RDY:Timeout(0x%x)"
#define  MT5931_INFO_437    "Destination:0x%08x/Length:0x%08x"
#define  MT5931_INFO_438    "[eHPItest]1.ChipID/RevisionID"
#define  MT5931_INFO_439    "[eHPItest]ChipID/RevisionID=%x"
#define  MT5931_INFO_440    "[eHPItest]1.ChipID/RevisionID"
#define  MT5931_INFO_441    "[eHPItest]ChipID/RevisionID=%x"
#define  MT5931_INFO_442    "wndrv_glue_info.ucCh_set_mode=%d"
#define  MT5931_INFO_443    "i=%d"
#define  MT5931_INFO_444    "ucRegClass=%d,ucBand=%d,ucChannelSpan=%d,ucFirstChannelNum=%d,ucNumChannels=%d"

#define  MT5931_INFO_501    "[READ]cr_offset_1:%xFail!"
#define  MT5931_INFO_502    "[READ]cr_offset:%x,cr_value:%x"
#define  MT5931_INFO_503    "[READ]cr_offset_2:%xFail!"
#define  MT5931_INFO_504    "[READ]cr_offset:%x,cr_value:%x"
#define  MT5931_INFO_505    "[WRITE]mcr_offset:%x,mcr_value:%x"
#define  MT5931_INFO_506    "wndrv_test_set_test_mode_req():%dms"
#define  MT5931_INFO_507    "wndrv_test_meta_rx_req():rxquerytimes:%d"
#define  MT5931_INFO_508    "wndrv_test_meta_tx_req():txquerytimes:%d"
#define  MT5931_INFO_509    "wndrv_test_chip_cr_rw():read:%d,cr_offset:%x,cr_value:%x"
#define  MT5931_INFO_510    "[READ]cr_offset:%xFail!"
#define  MT5931_INFO_511    "[READ]cr_offset:%x,cr_value:%x"
#define  MT5931_INFO_512    "[READ]cr_offset:%x,cr_value:%x"
#define  MT5931_INFO_513    "[WRITE]cr_offset:%x,cr_value:%x"
#define  MT5931_INFO_514    "Unexpectedcategory!"
#define  MT5931_INFO_515    "wndrv_test_get_conn_status()"
#define  MT5931_INFO_516    "wlanSendSetQueryCmd(CMD_ID_GET_CONNECTION_STATUS):status=%d"
#define  MT5931_INFO_517    "wndrv_test_set_ibss_channel():channelnum=%d"
#define  MT5931_INFO_518    "wndrv_prepare_test():#%d"
#define  MT5931_INFO_519    "WHISR=[%x]"
#define  MT5931_INFO_520    "response=[%x]"
#define  MT5931_INFO_521    "PollinWHISRfail"
#define  MT5931_INFO_522    "[eHPItest]RequestFW-Ownbackfailed!(times=%d)"
#define  MT5931_INFO_523    "[eHPItest]ehpitest_wifi_init"
#define  MT5931_INFO_524    "[eHPItest]ChipID=%x"
#define  MT5931_INFO_525    "INIT-RDYdetected"
#define  MT5931_INFO_526    "WaitingforInitReadybit:Timeout"
#define  MT5931_INFO_527    "FirmwaregetfromSDcard"
#define  MT5931_INFO_528    "Firmwaresizecapturefailed!"
#define  MT5931_INFO_529    "Firmwarefileopenfailed!"
#define  MT5931_INFO_530    "PLL-RDYdetected\n"
#define  MT5931_INFO_531    "WaitingforPLLReadybit:Timeout\n"
#define  MT5931_INFO_532    "[eHPItest]0.FirmwareDownload"
#define  MT5931_INFO_533    "Firmwarescatterdownloadfailed!"
#define  MT5931_INFO_534    "Firmwarefilereadfailed!"
#define  MT5931_INFO_535    "Firmwarescatterdownloadfailed!"
#define  MT5931_INFO_536    "DL_OKdetected\n"
#define  MT5931_INFO_537    "WaitingforDL_OK/DL_FAILbit:Timeout\n"
#define  MT5931_INFO_538    "wlanAdapterStart():WaitingforReadybit..\n"
#define  MT5931_INFO_539    "Readybitasserted\n"
#define  MT5931_INFO_540    "WaitingforReadybit:Timeout\n"
#define  MT5931_INFO_541    "[eHPItest]1.ChipID/RevisionID"
#define  MT5931_INFO_542    "[eHPItest]ChipID/RevisionID=%x"
#define  MT5931_INFO_543    "[eHPItest]2.RequestFW-Ownback"
#define  MT5931_INFO_544    "Test#1:FWcannotdothetest.\n"
#define  MT5931_INFO_545    "[eHPItest]>>WIFIHIFSYSLoopbacktest"
#define  MT5931_INFO_546    "[eHPItest]>>loopbacktestfail"
#define  MT5931_INFO_547    "[eHPItest]packetspass:%x"
#define  MT5931_INFO_548    "[eHPItest]Totalpacketspass:%x"
#define  MT5931_INFO_549    "[eHPItest]EachTestPaternpass:%x"
#define  MT5931_INFO_550    "[eHPItest]TXDMA->RXDMApass:%x"
#define  MT5931_INFO_551    "[eHPItest]TXDMA->RXMCUpass:%x"
#define  MT5931_INFO_552    "[eHPItest]TXMCU->RXDMApass:%x"
#define  MT5931_INFO_553    "[eHPItest]TXMCU->RXMCUpass:%x"
#define  MT5931_INFO_554    "[eHPItest]Packetsize200-1500loopcount:%x"
#define  MT5931_INFO_555    "wndrv_test_setquery_ant():query=%d,ant=%d"
#define  MT5931_INFO_556    "CurrentAntennapathisBT"
#define  MT5931_INFO_557    "CurrentAntennapathisWIFI"
#define  MT5931_INFO_558    "wndrv_test_chip_efuse():query=%d,offset=%d,value=%d"
#define  MT5931_INFO_559    "wndrv_test_on_off():u4IsTestMode=%d"
#define  MT5931_INFO_560    "wndrv_test_fw_dl_stress():u4IsTestMode=%d"
#define  MT5931_INFO_561    "wndrv_test_power_on():u4IsTestMode=%d"
#define  MT5931_INFO_562    "wndrv_test_power_on_off():u4IsTestMode=%d"
#define  MT5931_INFO_563    "wndrv_test_set_rx_event_port()"
#define  MT5931_INFO_564    "WLANRSSI=%d"
#define  MT5931_INFO_565    "wndrv_test_chip_swcr_dump(): category:%d, ucCate:%d, ucAction:%d, ucOpt0:%d, ucOpt1:%d"

#define  MT5931_INFO_600    "error! channel num=%d"
#define  MT5931_INFO_601    "ucOpt0 or ucOpt1 is too large"
#define  MT5931_INFO_602    "EHPI BUS ERROR @ TC_INDEX: %d --- %x: %x, %X: %X, %X: %X"

#define  MT5931_INFO_603    "PFSM _pfsm_rst %d.%d-->0.0"
#define  MT5931_INFO_604    "PFSM state %d.%d --> %d.0"
#define  MT5931_INFO_605    "PFSM IBSS/WDS data not support. %x"
#define  MT5931_INFO_606    "PFSM %02x %02x %02x %02x %02x %02x %02x %02x"
#define  MT5931_INFO_607    "PFSM sl:%d, pl:%d, m:%d, s_p:%s"
#define  MT5931_INFO_608    "sniffer:OnOff(%d),Channel(%d),Filter(0x%x),MinRcpi(%d),MaxRssi(%d),MinLen(%d),MaxLen(%d)"
#define  MT5931_INFO_609    "start smart_connect:OnOff(%d),Channel(%d),Filter(0x%x),MinRcpi(%d),MaxRssi(%d),MinLen(%d),MaxLen(%d)"
#define  MT5931_INFO_610    "smart_connect:OnOff(%d),Channel(%d),FilterOptions(0x%x),MinRcpi(%d),MaxRssi(%d),MinLen(%d),MaxLen(%d)"
#define  MT5931_INFO_611    "disable sniffer mode"
#define  MT5931_INFO_612    "Smart connection:get sync done,status=%d"
#endif




#endif /* _WNDRV_TRC_H */


