/*
 * Generated by MTK Easy PinMux Tool Version 1.0.2 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Tue Mar 22 13:42:18 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/


const char BSP_BIO_SENSOR_PPG_VDRV_EN = 11;


const char BSP_BIO_SENSOR_32K = 13;


const char BSP_BIO_SENSOR_RST_PORT_PIN = 14;


const char BSP_BIO_SENSOR_AFE_PWD_PIN = 15;


const char HAL_KEYPAD_COL1_PIN = 19;


const char HAL_KEYPAD_COL0_PIN = 20;


const char HAL_KEYPAD_ROW2_PIN = 21;


const char HAL_KEYPAD_ROW0_PIN = 23;


const char HAL_LCD_LSCK0_PIN = 40;
const char HAL_LCD_LSCK0_PIN_M_GPIO = 0;
const char HAL_LCD_LSCK0_PIN_M_LSCK0 = 1;
const char HAL_LCD_LSCK0_PIN_M_CMPDN = 3;
const char HAL_LCD_LSCK0_PIN_M_MA_SPI2_B_SCK = 9;


const char gpio_44_strapping_pin = 44;


const char gpio_46_strapping_pin = 46;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_KEYPAD_COL2_PIN = 0xff;
const char HAL_KEYPAD_ROW1_PIN = 0xff;
const char BSP_CTP_SCL_PIN = 0xff;
const char BSP_CTP_SDA_PIN = 0xff;
const char BSP_CTP_RST_PIN = 0xff;
const char BSP_CTP_EINT_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_GNSS_POWER_PIN = 0xff;
const char gpio_20_strapping_pin = 0xff;
const char gpio_40_strapping_pin = 0xff;
const char gpio_47_strapping_pin = 0xff;
const char gpio_48_strapping_pin = 0xff;



