/*
 * Generated by MTK Easy PinMux Tool Version 2.4.4 for 7687. Copyright MediaTek Inc. (C) 2015.
 * 2018-01-12 17:22:56:0391
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/
#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H


#endif /* _EPT_EINT_DRV_H */


