/*
 * Generated by MTK Easy PinMux Tool Version 1.0.2 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Tue Mar 22 13:42:18 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/


const unsigned char TEST_VAR_NAME1 = 7;
const unsigned char TEST_VAR_NAME2 = 10;
const unsigned char BSP_CTP_EINT = 0xff;
const unsigned char HAL_ACCDET_EINT = 0xff;
const unsigned char HAL_MSDC_EINT = 0xff;
const unsigned char BSP_GNSS_EINT = 0xff;




