/*
 * Generated by MTK Easy PinMux Tool Version 2.4.0 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2018-04-13 17:16:45:0399
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char BSP_BIO_SENSOR_PPG_VDRV_EN = 7;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_GPIO = 0;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_EINT = 1;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_MC1_A_DA1 = 2;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_SLA_EDICK = 3;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_UTXD2 = 4;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_BT_BUCK_EN_HW = 6;
const char BSP_BIO_SENSOR_PPG_VDRV_EN_M_MA_SPI0_B_MISO = 7;


const char BSP_GNSS_POWER_PIN = 10;
const char BSP_GNSS_POWER_PIN_M_GPIO = 0;
const char BSP_GNSS_POWER_PIN_M_EINT = 1;
const char BSP_GNSS_POWER_PIN_M_AUXADCIN_4 = 2;
const char BSP_GNSS_POWER_PIN_M_BT_PRI = 9;


const char BSP_BIO_SENSOR_32K = 14;
const char BSP_BIO_SENSOR_32K_M_GPIO = 0;
const char BSP_BIO_SENSOR_32K_M_EINT = 1;
const char BSP_BIO_SENSOR_32K_M_CLKO = 2;
const char BSP_BIO_SENSOR_32K_M_MA_EDICK = 3;
const char BSP_BIO_SENSOR_32K_M_MA_SPI1_B_MISO = 4;
const char BSP_BIO_SENSOR_32K_M_PWM3 = 5;
const char BSP_BIO_SENSOR_32K_M_SLA_EDICK = 6;


const char BSP_CTP_EINT_PIN = 15;
const char BSP_CTP_EINT_PIN_M_GPIO = 0;
const char BSP_CTP_EINT_PIN_M_EINT = 1;
const char BSP_CTP_EINT_PIN_M_PWM4 = 5;


const char BSP_BIO_SENSOR_RST_PORT_PIN = 29;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_GPIO = 0;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_CMCSK = 1;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_LPTE = 2;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_CMCSD2 = 4;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_EINT = 5;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_MC1_B_DA1 = 8;


const char BSP_CTP_SCL_PIN = 36;
const char BSP_CTP_SCL_PIN_M_GPIO = 0;
const char BSP_CTP_SCL_PIN_M_SCL0 = 1;
const char BSP_CTP_SCL_PIN_M_SCL1 = 2;


const char BSP_CTP_SDA_PIN = 37;
const char BSP_CTP_SDA_PIN_M_GPIO = 0;
const char BSP_CTP_SDA_PIN_M_SDA0 = 1;
const char BSP_CTP_SDA_PIN_M_SDA1 = 2;


const char BSP_SPEAKER_EBABLE_PIN = 45;
const char BSP_SPEAKER_EBABLE_PIN_M_GPIO = 0;
const char BSP_SPEAKER_EBABLE_PIN_M_SRCLKENAI = 1;


const char BSP_CTP_RST_PIN = 47;
const char BSP_CTP_RST_PIN_M_GPO47 = 0;
const char BSP_CTP_RST_PIN_M_MA_SPI1_CS1 = 1;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char BSP_CTP_SW_I2C_SCL_PIN = 0xff;
const char BSP_CTP_SW_I2C_SDA_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;
const char BSP_WIFI_32K_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char BSP_WIFI_RESET_PIN = 0xff;
const char BSP_WIFI_ENABLE_PIN = 0xff;
const char BSP_HP_ANA_SW_PIN = 0xff;
const char UPDATE_HOST_STATUS_PIN = 0xff;
const char QUERY_MODEM_STATUS_PIN = 0xff;
const char NOTIFY_MODEM_EXCEPTION_PIN = 0xff;
const char TRIGGER_MODEM_RESET_PIN = 0xff;
const char NOTIFY_MODEM_WAKEUP_PIN = 0xff;
const char TRIGGER_MODEM_START_PIN = 0xff;
const char TRIGGER_MODEM_WAKEUP_PIN = 0xff;
const char BSP_LED0_PIN = 0xff;
const char BSP_LED1_PIN = 0xff;
const char BSP_LED2_PIN = 0xff;
const char BSP_EINTKEY0_PIN = 0xff;
const char BSP_EINTKEY1_PIN = 0xff;
const char BSP_EINTKEY2_PIN = 0xff;


const char HAL_KEYPAD_COL2_PIN = 0xff;
const char HAL_KEYPAD_COL1_PIN = 0xff;
const char HAL_KEYPAD_COL0_PIN = 0xff;
const char HAL_KEYPAD_ROW2_PIN = 0xff;
const char HAL_KEYPAD_ROW1_PIN = 0xff;
const char HAL_KEYPAD_ROW0_PIN = 0xff;
const char HAL_I2S_MASTER_EDIDO_PIN = 0xff;
const char HAL_I2S_MASTER_EDIDI_PIN = 0xff;
const char HAL_I2S_MASTER_EDIWS_PIN = 0xff;
const char HAL_I2S_MASTER_EDICK_PIN = 0xff;





